### ISSUE TITLE
How to map and transfer new data to cr-birding

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#104]
Due to difficulties to add our data in cr-birding dbase, the transfer of data was not as smooth and fast as expected. INBO experts had no choice than adding data to INBO database again as they were getting way too much.

Based on previous phone communication with Lisenka (15 May), we agreed to send a new mapped version of INBO data to SOVON, containing "old" and "new" data (users, birds, obs). This new dumping will be sent after Jeroen (from SOVON) will accomplish adding "old" data to cr-birding dbase. 

@EricStienen pointed out that there are also "modified" data (solved inconsistencies or errors in INBO dbase) although these changes are minimal in comparison with new ones. 

To be sure, I would like to know directly from Jeroen if he agrees with this strategy.

**Comment by JeroenNienhuis** [comment]
Adding additional data is ok. I don't prefer updating modified data, since I have to process all data again. I also updated records myself (mainly adding coordinates). Is it possible to send just updated records?

**Comment by damianooldoni** [comment]
Ok, thanks, @JeroenNienhuis. I will not send old data again, just the new ones (new obs, new rings, new users) or updated ones.

**Comment by damianooldoni** [comment]
From end of October I will surely work on processing of the new INBO ring data. It can be that I will start earlier, but I don't want to be too optimistic about my plannings. 

However, before I start, we have to decide which data specification changes you require to be able to move the new data into SOVON db in a time span of ~2 weeks. The date of sending data will be beforehand discussed with @JeroenNienhuis , Lisenka, Eric and his team as done before. So, @JeroenNienhuis: based on the experience learned from first mapping, do you think there is something I have to change in my data processing to make your workload easier next time?

**Comment by damianooldoni** [comment]
This issue is outdated and too general. I will close as smaller issues are better to tackle and have been written in the meantime.
