### ISSUE TITLE
Zilvermeeuw spec - Larus argentatus

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#106]
Issue found by @EricStienen while checking the data in cr-birding database:
> Zilvermeeuw wordt in bij de soortselectie van SOVON en ook in de lifelist omschreven als `Zilvermeeuw spec - Larus argentatus`, kleine mantelmeeuw als `Kleine Mantelmeeuw - Larus fuscus`.  `Zilvermeeuw spec - Larus argentatus` zou moeten worden `Zilvermeeuw - Larus argentatus`.

Lisenka, @JeroenNienhuis: could you please check this?

**Comment by JeroenNienhuis** [comment]
species name updated

**Comment by damianooldoni** [comment]
@JeroenNienhuis : thanks a lot for fast reply. 

@EricStienen : could you please doublecheck and close issue if done? Thanks.

**Comment by EricStienen** [comment]
Thanks. issue can be closed.

**Comment by EricStienen** [comment]
@damianooldoni I can not close the issue (or I can not find how to do it). probbaly only the author can close issues.
