### ISSUE TITLE
Order of color and text of inscription

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#107]
After checking the very first test version of ring data @EricStienen found that:
>  Shorthand code is raar en komt niet overeen met andere soorten zoals bijvoorbeeld grote stern. Bijvoorbeeld shorthand code voor LMA.N is BW (LMA.N). Dat zou moeten zijn B-LMA.N (analogie met grote stern bijvoorbeeld).

@EricStienen : as I wrote in the mapping ([5.2.13 Map color of rings and inscriptions](https://inbo.github.io/cr-birding/3_birds.html#map-color-of-rings-and-inscriptions)), SOVON asked to map the color ring as follows: 
> The bird_shorthand should be composed of: 
> 1. color of the ring 
> 2. color of the inscription 
> 3. inscription

Lisenka, @JeroenNienhuis: is there a reason why the order of color and text of inscription should be different among species? Or is it a difference due to the fact that the tern mentioned by @EricStienen has two rings, where the second has only a color without text? See comment of Lisenka about mapping of color of rings and inscriptions here: https://github.com/inbo/cr-birding/issues/59#issuecomment-472855970.

**Comment by JeroenNienhuis** [comment]
I asked  for shorthands like B-LMA.N from the start. Someone else decided it had to be like BW(LMA.N). Can I change the shorthands to the format mentioned first for gulls as well as Cormorants and Pied Avocets?

**Comment by damianooldoni** [comment]
It would be better to follow a (documented) standard, valid for all type of rings along all projects and improve ALL data in db based on such standard, I think. A solution could be to map old data to new standard. But it is not always possible for several reasons.

It is up to SOVON to make a hard decision on it and stick to it. @JeroenNienhuis: discuss it with Lisenka and/or other SOVON experts. Obviously some users would find strange to have different notation standards for different projects/birds. Let me know about SOVON final decision.

About INBO data, I will not change my mapping at this stage of the project, otherwise all ring data will result updated and I will have problems filtering the real new/updated ones and the old ones.

**Comment by JeroenNienhuis** [comment]
I still prefer a format like B-LMA.N since it is clearer for the observers. Current observations can be updated. In the future files to be updated should contain the correct shorthand (or a bto-code). For the new data since April you can use the old shorthand notation and I will change it to the new one once. After that it should be possible to update the shorthands in your database. (Am I right?)

**Comment by damianooldoni** [comment]
Great. @JeroenNienhuis, do as you/SOVON prefers about the order of colors/text of inscription.
And as you said, I will not change my workflow for the updated/new data since April, thanks.

Little remark: the INBO database will be not maintained anymore after we switch to cr-birding. So, no need of:
> After that it should be possible to update the shorthands in your database. (Am I right?)

**Comment by LisenkadeVries** [comment]
I am very sorry, for some reason I was under the impression that the INBO database contained a inscriptiekleur field that you wanted to include, which is why i provided the explanation of the bird shorthand code with the inscription color (https://github.com/inbo/cr-birding/issues/60). 

I guess I misunderstood the question. My apologies.

**Comment by damianooldoni** [comment]
@LisenkadeVries: no apologies needed and very welcome to GitHub community! You are completely right. We have a field called `InscriptieKleurCode` which we wanted to maintain as well, at least I thought. I misunderstood the issue of @EricStienen: I thought that the `N` at the end was the color of inscription but it is not true: it is part of the inscription.

@EricStienen: please clarify your doubts. If no color of inscription was added to sandwich tern, it doesn't mean that we don't have to add such information to thousands of other birds where such information is present.

**Comment by JeroenNienhuis** [comment]
@damianooldoni, what do you mean with "preferences of the order color/text of inscription"?

@damianooldoni , you mention that the current database will not be mailtained after adding the data to the website. What are the plans for adding newly ringed birds. I guess that catches will be in one of more tables at INBO and added tot the website occasionally.

In almost no project the inscription color is  a distinctive characteristic of a bird. Almost no project coordinator uses inscription color to name a bird. Almost always light colored rings have a black inscription en dark rings have a white inscription. It is possible to enter inscription color when using the generic input, but at the moment birds are also matched if the inscription color differs from the project (after looking for an exact match with what the observer entered). If the importance of inscription color as a distinctive characteristic increases we will act on that. For example by mentioning inscription colors for a project and using this color when drawing markers of a bird on the screen.

**Comment by damianooldoni** [comment]
> @damianooldoni, what do you mean with "preferences of the order color/text of inscription"?

yes, I made some confusion while reading @EricStienen note... Nevermind. 
But now I see that maybe there was an error in his note as well. He wrote:

> Dat zou moeten zijn B-LMA.N

instead of 

*Dat zou moeten zijn BW-LMA.N*

So, I think his point was not the presence of the W after the B, but the use of space and brackets instead of hyphen `-`.  So, the question to be solved by this issue is: does SOVON will choose BW(LMA.N) or BW-LMA.N? 
sorry @LisenkadeVries for bringing you to misunderstand the issue as well. Please, @EricStienen: could you confirm this?

About second part:
> @damianooldoni , you mention that the current database will not be maintained after adding the data to the website. What are the plans for adding newly ringed birds. I guess that catches will be in one or more tables at INBO and added tot the website occasionally.

Well, instead of adding new rings in INBO database at the end of the day, they will add them to cr-birding. In any case, this is out of scope of this issue.

**Comment by JeroenNienhuis** [comment]
@damianooldoni, you just wrote "does SOVON choose BW(LMA.N) or BW-LMA.N?", but @EricStienen was cited in the first item of this issue "Dat zou moeten zijn B-LMA.N (analogie met grote stern bijvoorbeeld)." So the question should be "does SOVON choose BW(LMA.N) or B-LMA.N?" (without inscription color). The answer would be "B-LMA.N" (ringcolor+hyphen+inscription).

**Comment by damianooldoni** [comment]
Thank you @JeroenNienhuis! I understand the point now 100%.

As the text color is not important in any project, it's fine to me to not have it in the shorthand, same as for all other projects as well. 

Again, sorry for the mess I did in this issue.
