### ISSUE TITLE
Add coordinates to lifelists

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#109]
@EricStienen: 
> De lifelists dienen ook de coordinaten van de waarneming te bevatten. Dit is vooral van belang voor nieuwe waarnemingen. Omdat mensen via de birdring app en het kaartje op de submit site hun gegevens gaan invoeren gaat er in de omschrijving zeer regelmatig zaken staan als "unnamed road, Netherlands". Dat is erg vaag en de exacte coordinaten zijn dus wenselijk.

I agree. It would be an important enhancement of the user experience.

@JeroenNienhuis: is it something SOVON can manage easily?

**Comment by JeroenNienhuis** [comment]
Is is not difficult to add. The problem is the space. If I add coordinates I have to remove or shorten another column. Besides, without help most observers have no idea where to find e.g. 3.220E 51.319N

**Comment by EricStienen** [comment]
would be nice if this could be added (maybe in a smaller character size?). I am sure that all observers are able to find the coordinates, it is much harder to find "unnamed road, Netherlands". When birds have short lifelists that is not a problem because you can easily find it on the maps that are included in the lifelist, but some birds have over 200 recoveries and the maps are no longer very informative.

**Comment by JeroenNienhuis** [comment]
I don't agree with "some birds have over 200 recoveries and the maps are no longer very informative". You can see clusters of observations. It is possible to click an individual marker on the map and you get date and location name. In the table you will find a Info-button for each observation. If you click it you wil see details of the observation.

**Comment by EricStienen** [comment]
indeed my terminology "no longer informative" was not very well chosen. The thing is that it is hard to find a single observation between the many markers. And more importantly that the description of the observation will no longer be very consitent and sometimes not very straightforward (many "unnamed roads"). In contrast, coordinates are always straightforward.

Is it problematic to add the coordinates in the life-list? Maybe there is room to decrease the character size of all columns?

**Comment by JeroenNienhuis** [comment]
All unnamed roads come from the BirdNest app. In counted just 262 times "Unnamed road" without further town or city compared to about 750 unnamed roads with city/town and almost 19.000 named locations from the app. So "Unnamed road, Nederland" is about 1.5% of all app-input. If you look at the life history on the website you can always use the link to the original observation (with a map with a marker).
I can see what I can do, but I do not put it high on my to-do list if you don't mind.

**Comment by JeroenNienhuis** [comment]
In the previous post I wrote BirdNest, but of course I ment BirdRing app. Today Mario (programmer of the app) wrote that "unnamed roads" are history, so I think coordinates in the live history are no longer needed. I shall update the current "unnamed roads" to something more meaningful.

**Comment by damianooldoni** [comment]
@JeroenNienhuis : is this solved?

**Comment by JeroenNienhuis** [comment]
I guess so. BirdRing is updated. Old locations "Unnamed Road, Nederland" are updated. It might that some app users are still working with older versions, but that will change in the future.

**Comment by damianooldoni** [comment]
Thanks.
