### ISSUE TITLE
Mapping of bird shorthand

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#11]
The columns `Nummer`, `Nummer_Nieuw` and `Nummer_Desc` from table `tblKleurring` contain information related to SOVON's column `bird_shorthand` (in `crbirding_birds` worksheet), the color ring number.

Eric and Marc question: 
> mag `bird_shorthand` meerdere codes bevatten voor hetzelfde individu? Bijvoorbeeld comma separated? In onze databank,zijn er drie kolommen Nummer, NummerNieuw, NummerDesc omdat we gegevens over verschillende, soms heel oude kleurringen hebben.

The main problem in doing it is that the final data frame will be unitidy. 
It seems also not needed: no values of `kleurringNummer` in table `tblWaarneming` which are present in column `NummerDesc` or `NummerNieuw` of `tblKleurring` but not in `Nummer`. My idea is to add values of `NummerNieuw` and `NummerDesc` to extra column `bird_notes` (if they are different than value in `Nummer`).

Answer of SOVON (Lisenka) underlines an important aspect: 

> Voor `cr_birding` is eigenlijk alleen de huidige kleurringcode van belang, want dat is degene die in het veld afgelezen kan worden. De oudere codes kunnen inderdaad in een kolom  birds_notes gezet worden.

In other words, the values of `kleurringNummer` (in `tblWaarneming`) play the decisive role in deciding what we should use as `bird_shorthand`.

Eric, Marc: what do you think about it?

**Comment by damianooldoni** [comment]
Extracts from the very exhaustive Eric's answer:

> De huidige kleurring-code is OVERIGENS `Nummer_Nieuw` en niet `Nummer`.

> Er moet een link blijven bestaan (extra kolommen) met de oude code, `Nummer` en met de puntnotitie (`Nummer_Desc`)

He explains also why:
> Niet alle waarnemers noteren de punt en ook wordt de punt niet altijd waargenomen. Tenslotte kan het voorkomen dat een waarnemer een kleurringcode doorgeeft die niet meer bestaat, maar op het moment van aflezen wel. Feitelijk MOETEN er dus 3 entries zijn voor de waarnemer. Ze moeten zowel  `Nummer`, `Nummer_Nieuw` and `Nummer_Desc` kunnen ingeven.

He adds a very illustrative example for it:
> Hypothetisch voorbeeld.  `Nummer`: `AMAS`. Die had lange tijd de ring met code `AMAS` (`Nummer`), maar werd op 1 juli 2018 gevangen en omdat de oude ring heel erg versleten was kreeg die een gloednieuwe ring `CZAD` (`NummerNieuw`), waarop een punt staat tussen C en Z, dus `C.ZAD` (`NummerDesc`).
> Nu krijgen we op 01 oktober drie meldingen van dit indvidu:
>1. een melder die op 1 mei 2018 `AMAS` heeft afgelezen.
>2. een melder die op 15 juli 2018 `CZAD` heeft afgelezen.
>3. een melder die op 3 september `C.ZAD` heeft afgelezen.
> 
> Hoewel ze dus een verschillende code doorgeven, moeten al deze melders worden opgevangen door het CR-submit systeem en moeten ze alle drie terecht komen bij hetzelfde individu.

**Comment by damianooldoni** [comment]
SOVON antwoord:

> Ik heb het even overlegd met degene die de daadwerkelijke input in Cr birding submit regelt. Hij gaf de volgende oplossing. Op het tabblad `crbirding_birds` vind u de kolommen `bird_date_begin` en `bird_date_end`. Achter de kolom `bird_date_end` kunt u een extra kolom invoegen genaamd `bird_rings_changed`. In de kolom `bird_date_begin` kunt u voor de vogel met code `AMAS` de ringdatum invullen. In de kolom `bird_date_end` kunt u de datum aangeven waarop de vogel een nieuwe ring kreeg, in dit geval 1 juli 2018. Op een volgende regel kunt u voor de vogel met code `C.ZAD` in de kolom `bird_date_begin` de ringdatum invullen, in dit geval 1 juli 2018. In de nieuw toegevoegde kolom `bird_rings_changed` kunt u voor deze vogel aangeven dat op de begindatum een nieuwe kleurring is toegevoegd, waarbij `1` = alleen nieuwe kleurringen en `2` = zowel nieuwe kleurringen als een nieuwe metalen ring:

Bird_shorthand | bird_date_begin | bird_date_end | bird_rings_changed
--- | --- | --- | ---
AMAS | 02-05-2016 (fictief) | 01-07-2018 |                                    
C.ZAD | 01-07-2018 | | 1

> `bird_id` hoeft u niet in te vullen, deze kolom is vergelijkbaar met `bird_reference` en wordt door ons ingevuld.

**Comment by damianooldoni** [comment]
Nice. This is going to the right direction, I find.
Now, the second part of the story: how do we link `AMAS` and `C.ZAD` so that they refer to the same bird? 

This is of extreme importance for everybody, I think. Although we cannot use `bird_id` (I totally agree with it) and `bird_reference` maybe why not use a kind of internal reference id (a progressive number)? Something like this:

Bird_identifier | Bird_shorthand | bird_date_begin | bird_date_end | bird_rings_changed
--- | --- | --- | --- | ---
100 | AMAS | 02-05-2016 (fictief) | 01-07-2018 |                                    
100 | C.ZAD | 01-07-2018 | | 1

If this is the 100th bird ever ringed added to the database.

The name `bird_identifier` can be changed if you want, I don't mind. Thanks to this kind of internal identifier we can link our birds to our observations. As we may not use `bird_id` and `bird_reference`, I don't find any straight way for doing it unless adding an internal id. Suggestions are welcome.

I will discuss the presence of a version with a point (`C.ZAD`) and without it(`CZAD`) in a separate issue.

**Comment by damianooldoni** [comment]
Lisenka's answer:

> Voor het koppelen van de herringde vogels wordt inderdaad een soort van internal reference ID gebruikt, de `bird_reference`. Deze wordt ook gebruikt om het ringmoment en de waarnemingen aan elkaar te koppelen. Daarnaast wordt deze gebruikt wanneer op een later moment nieuwe waarnemingen vanuit een database moeten worden toegevoegd.  Hierbij krijgt elke geringde vogel een unieke code. Deze unieke code wordt vervolgens ook bij de waarnemingen ingevuld, waardoor deze waarnemingen aan de juiste geringde vogel kunnen worden gekoppeld.

> Tot nu toe heb ik hem vaak zelf ingevuld, omdat ik heb gemerkt dat er vaak veel vragen zijn over hoe het precies werkt. Vandaar dat ik in eerste instantie aan heb gegeven dat deze niet ingevuld hoeft te worden.

> Uw uitleg over de `bird_identifier` is echter precies wat ik bedoel. **Wat mij betreft kunt u deze waarde dus gebruiken als internal identifier en kunt u deze waarde invullen in de kolom `bird_reference`**.

**Comment by EricStienen** [comment]
perfect

**Comment by damianooldoni** [comment]
I leave it open until it is implemented.
