### ISSUE TITLE
Add filter on ringcode

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#110]
@EricStienen proposal for improving the user's experience:

> Er zou een filter moeten zijn op ringcode. Mensen zoeken vaak een specifieke meeuw en nu kunnen de meest ervaren waarnemers die niet terugvinden in de lange lijsten.

@JeroenNienhuis: what do you think about it?

**Comment by JeroenNienhuis** [comment]
There are filters on multiple pages. For personal observation from the menu:"My birds", "My observations". For admins: "Birds", "Observations", "Unmatched observations"). On what page you are missing filters?

**Comment by EricStienen** [comment]
On both filters! I can not search for a specific bird-ID.

**Comment by JeroenNienhuis** [comment]
@EricStienen, pleace clearify.
Choose "my birds" from the menu and you can filter on birds,, species, dates
Choose "my observations" from the menu and you can filter on birds,, species, dates
Choose "birds" from project page and you can filter on birds
Choose "observations" from project page and you can filter on birds, species, dates, observers
For a filter on birds you can also use partial codes.

**Comment by EricStienen** [comment]
My mistake! I used the wrong shorthand code to filter. It works perfectly! Thanks.

**Comment by EricStienen** [comment]
@damianooldoni : item can be closed.
