### ISSUE TITLE
Year of Birth is missing

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#113]
@EricStienen: 
> Year of Birth should be indicated correctly . e.g. for BW(AAAZ) it is now indicated that year of birth is not known. However according to the INBO-database this bird was ringed as a pullus at 02/07/1999. 

In my final ring file, [crbirding_birds_20190410.csv](https://github.com/inbo/cr-birding/blob/master/data/processed/crbirding_birds_20190410.csv), I can read indeed the same:

bird_reference | bird_euring | bird_shorthand | bird_ring_number | bird_date_begin | bird_date_end | 
-- | -- | -- | -- | -- | --
348 | 05910 | BW(AAAZ) | L...904847 | 02-07-1999 | 06-06-2006 

@JeroenNienhuis: are you maybe still working on this field? Thanks.

**Comment by JeroenNienhuis** [comment]
In the datafile with birds I received there are 2 lines for this individual (different colorcodes). Neither had information about the year of birth

bird_id,bird_reference,bird_euring,bird_bto,bird_shorthand,bird_scheme,bird_ring_number,bird_name,bird_sex,bird_birth_year,bird_date_begin,bird_date_end,bird_rings_changed,bird_age_ringing,bird_ring_position,bird_ring_direction,bird_notes
,348,05910,,BW(AAAZ),BLB,L...904847,,M,,02-07-1999,06-06-2006,2,1,,,
,348,05910,,BW(D.FAY),BLB,L...904847,,M,,06-06-2006,,1,A,RB,U,

**Comment by JeroenNienhuis** [comment]
I have added a year of birth based on the ringing date and the age at ringing for all birds with known age.

**Comment by damianooldoni** [comment]
Based on Excel file I got from Lisenka, we should not fill the field `bird_birth_year` as it will be filled by SOVON. So, is it ok if we leave it empty in the new mapping as well?

**Comment by JeroenNienhuis** [comment]
That is ok if you have EURNG values for bird_age_ringing (https://euring.org/files/documents/E2000PLUSExchangeCodeV117.pdf#page=14)

**Comment by damianooldoni** [comment]
Yes, indeed. I have just checked that we miss that field for 142 rings, typically birds where a ring is changed. I will fill it by calculating the date difference. Hopefully it gets solved easily.

**Comment by JeroenNienhuis** [comment]
I think that it should be ok of you only give an age the first time a bird is caught. If a bird is re-ringed you should sent 2 (or more) records. We'll see if that is enough. I don't think it is a good idea if you calculate the age on the recapture date from the age at ringing and the time since ringing.

**Comment by damianooldoni** [comment]
Thanks @JeroenNienhuis. 

There are only three birds (Larus, EURING 05910) ringed just once and without age while ringing.
From `tblWaarneming`:

Datum | KleurringNummer | LeeftijdCode
--- | --- | ---
2013-06-04 | GPS19 | 
2015-08-10 | MGAG |
2015-08-10 | PNAN |

@EricStienen: could you please check it?

**Comment by EricStienen** [comment]
solved at DB level

**Comment by damianooldoni** [comment]
Indeed, solved. Check added in data processing.
