### ISSUE TITLE
Observations field status missing

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#114]
Report from @EricStienen:
> The fact that a bird was recorded breeding is nowhere indicated. e.g. BW(AAAZ) was recorded breeding at 13/05/2002.

In order to standardize our data according to [EURING Exchange Code 2000+](https://euring.org/files/documents/E2000PLUSExchangeCodev1161.pdf), we agreed with @LisenkadeVries to add field *status*, which was originally not in the template. See #19 about it.

Speaking about the bird @EricStienen refers to in the example above, I can find in text file `cr-birding_observations_20190410.csv` that this bird was breeding at 13-05-2002, indeed:

observation_reference | bird_reference | status | observation_date
-- | -- | -- | --
6383 | 348 | N | 13-05-2002

Status values present in our data: `N`, `-` and `U`.

@JeroenNienhuis: is this field maybe still to be mapped maybe? Thanks a lot for your help.

**Comment by JeroenNienhuis** [comment]
There is no standard field for "status". The number of standard fields is limited. Instead we have a number of "extra variables". A variable has a name and some properties. It can be a dropdown with lookup values or a field that can be filled with a text or a number. To prevent wild groth of variables and variablenames I manage the variables. Within a project extra viariables can be chosen and linked to observations or catches or both. Adding a variable for EURING status field is possible. I have to think about how data must be imported, but I can import data directly in the database. Are there questions you want to ask your observers when they enter observations?

**Comment by damianooldoni** [comment]
Thanks @JeroenNienhuis for explaining me about the standard and extra variables. I understand perfectly your concerns about wild growth of fields in db. :+1: For this reason we try to limit us to EURING fields.

>  Are there questions you want to ask your observers when they enter observations?

We thought about the EURING variable `status` in order to match as better as possible the existing information in our db. So, I think this information should be asked our observers in the future as in the past. If I understood correctly, @EricStienen and bird teams at INBO are very interested about nesting.

**Comment by JeroenNienhuis** [comment]
There are already 2 variables with amongst others information about breeding:

behaviour with options: "aggression over food", "unknown", "alarming", "copulating", "with chicks", "courtship behaviour", "foraging", "fighting", "flying over", "breeding", "nest building", "preening", "resting/sleeping", "vigilant", "see notes"

breeding certainty with options: "pair in breeding habitat", "probable nesting site", "alarming", "nesting", "parent(s) with chick(s), outside nest", "parent(s) with chicks, in nest", "unknown", "certainly not", "in possible breeding habitat", "

Both developed with waders in mind and I guess way to detailed for you. When I look at the EURING field Status also has some useless options. The best option is to alter the EURING field options as follows:
bird not full grown -> rename "not applicable (chick)"
Unknown or unrecorded -> OK
Nesting or Breeding -> OK (perhaps rename to "breeding bird" (not interesting in only nest building or incubating)
Roosting assemblage -> omit (for now)
In Colony (not necessarily breeding but not pullus) -> split in "in colony, not breeding" and "in colony, unknown if breeding"
Moulting assemblage (whether bird moulting or not) -> omit (for now)
MoulTing -> omit (for now)
Apparently a Local bird, but not breeding -> rename "not a breeding bird"
Apparently a bird Wintering in the locality -> omit (we have a date, so "outside breeding season" is not needed
On Passage -> omit
At Sea -> omit
If "in colony" is splitted it gives more information al it is always possible to generate the correct EURING code.
What do you think?

**Comment by EricStienen** [comment]
good proposal!

**Comment by JeroenNienhuis** [comment]
Added a field "status full-grown bird" 2 weeks ago with values:
- | not applicable (chick)
U | unknown or unrecorded
N | breeding bird
L | not a breeding bird
KL | in colony, not breeding
KU | in colony, unknown if breeding
The first character is equal to the EURING variable "status". There are 2characters if the original EURING field is split in two.

**Comment by damianooldoni** [comment]
Getting back to this field. 
@JeroenNienhuis: should I rename the column `status` to `status_full_grown_bird` then? 

In our mapping we use these values:
- `N`, breeding bird (observations linked to actions `br` or `vang`)
- `-`, pullus (@JeroenNienhuis: based on your scheme, should I leave it empty, isn't?)
- `U` all other observations

@EricStienen: I don't think we need to change anything in our mapping up to now. We don't have information about colony in our db. Am I correct?

**Comment by JeroenNienhuis** [comment]
Yes, rename it tot status_full_grown_bird.
For pulli use a hyphen. In my comment on 28 June 2019 my hyphen was replaced by a bullet.

**Comment by damianooldoni** [comment]
All mapping run again and website updated by f353a4e986fd01ebc790661c7cfc025dd65e5db7. Issue can be closed.
