### ISSUE TITLE
Observation without action

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#116]
Hi @EricStienen 

I found this observation without link to any action:

Nummer | Datum | EuringCode | LeeftijdCode | WaarnemerNummer
--- | --- | --- | --- | ---
141511 | 2019-07-20 | 04560 | AD | 1611

Could you or someone of your team check it? Thanks :+1:

**Comment by EricStienen** [comment]
No Larus species, so I am not responsible for this.

**Comment by damianooldoni** [comment]
Indeed, you are right, it's a pied avocet: I will contact Geert Spanoghe. Thanks again.

**Comment by damianooldoni** [comment]
Geert Spanoghe contacted by e-mail on Mon, Mar 16, 5:16 PM.

**Comment by damianooldoni** [comment]
Observation has been removed from db. Issue solved.
