### ISSUE TITLE
Birds without any observation

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#117]
These three birds have no link to any observation:

Nummer | NummerNieuw | NummerDesc | Plaats | RingKleurCode | EuringCode | MetaalRingLandCode |
--- | --- | --- | --- | --- | --- | --- 
HAOW | HAOW | H.AOW | RU | B | 5910 | BE
EAYH | EAYH | EAYH | LU | W | 04560 | 
EAYE | EAYE | EAYE | LU | W | 04560 | 

@EricStienen : could somebody check it, please? Thanks!

**Comment by EricStienen** [comment]
EAYH en EAYE are not Larus. I assume that they can be deleted. Marc VDW is sorting out what happened to HAOW.

**Comment by damianooldoni** [comment]
You are right. I will contact Geert Spanoghe about EAYH and EAYE.

**Comment by EricStienen** [comment]
HAOW is solved at DB level

**Comment by damianooldoni** [comment]
Yes, @EricStienen . I confirm that. 
About other two birds (EAYH and EAYE) I contacted Geert Spanoghe by e-mail on Mon, Mar 16, 5:10 PM

**Comment by Geert282** [comment]
You can delete EAYH and EAYE

**Comment by EricStienen** [comment]
Done. Deleted EAYH and EAYE from the DB

**Comment by damianooldoni** [comment]
Indeed. Thanks @Geert282 and @EricStienen. I close this issue.
