### ISSUE TITLE
duplicates rngkl and rngme

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#118]
Birds `HAOC` and `HDOH` have both two observations with action `rngkl` and `rngme`:

Nummer | Datum | EuringCode | LeeftijdCode | KleurringNummer | WaarnemerNummer | AanmaakDatum
--- | --- | --- | --- | --- | --- | --- |
142237 | 2019-08-05 | 5910 | J1 | HAOC | 416 | 2019-08-19 12:34:00 UTC
144743 | 2019-08-05 | 5910 | J1 | HAOC | 416 | 2019-09-27 11:37:00 UTC
146035 | 2019-09-09 | 5910 | PU | HDOH | 416 | 2019-10-30 14:27:00 UTC
146036 | 2019-09-09 | 5910 | PU | HDOH | 416 | 2019-10-30 14:27:00 UTC

As `rngkl`/`rngme` is used for the applying of the very first color/metal ring, it should be present only once.

@EricStienen: could you or somebody of your team check it; please? thanks :100:

**Comment by EricStienen** [comment]
solved at the database level

**Comment by damianooldoni** [comment]
Check. Great job, thanks!

**Comment by damianooldoni** [comment]
I found a bird  with two observations with actions `rngkl` and `rngme`. Not at the same date as the two mentioned above, but still there should be only one obs with action `rngkl` per bird, isn't?

Extract from observation table:

Nummer | Datum | EuringCode | KleurringNummer | LeeftijdCode |AanmaakDatum
--- | --- | --- | --- | --- | ---
141607 | 2019-06-28 | 5910 | GVOK | PU | 2019-07-30 12:11:00
145003 | 2019-07-01 | 5910 | GVOK | PU | 2019-09-27 13:54:00

@EricStienen: could somebody from your team check it, please? Thanks.

**Comment by EricStienen** [comment]
Solved at the DB level.

**Comment by damianooldoni** [comment]
Indeed, thanks! :+1:  Issue can be closed again.

**Comment by damianooldoni** [comment]
While mapping the date of applying the very first color ring (obs linked to action `rngkl`), I found two duplicates for two rings, KKOZ and KZAG.

Extract from observation table:

Nummer | Datum | EuringCode | KleurringNummer | LeeftijdCode |AanmaakDatum
--- | --- | --- | --- | --- | ---
150583 | 2020-05-29 | 5910 | KKOZ | AD | 2020-07-09 13:08:00	
150581 | 2020-05-26 | 5910 | KKOZ | AD | 2020-07-09 13:04:00
45654 | 2009-05-22	| 05910 | KZAG | AD | 2009-07-15 16:08:00
108840 | 2015-05-26 | 5920 | KZAG | AD | 2015-09-11 14:51:00

Notice also different euring codes in the two rows related to KZAG ring.

@EricStienen: could somebody check this, please? Thanks.

**Comment by EricStienen** [comment]
solved at DB-level

**Comment by damianooldoni** [comment]
I can confirm it. Thanks. I close the issue.

**Comment by damianooldoni** [comment]
I am afraid I found a new duplicate for actions `rngkl` and `rngme`. Observations with `Nummer` 152601 and 154408 are both linked to actions `rngkl` and `rngme` for the bird with `KleurringNummer` LJOA. More details in the table below

Nummer | Datum | EuringCode | KleurringNummer | LeeftijdCode |AanmaakDatum
--- | --- | --- | --- | --- | ---
152601 | 2020-07-13 | 5920 | LJOA | J1 | 2020-08-24 14:36:00	
154408 | 2020-08-28 | 5920 | LJOA | J1 | 2020-09-21 11:55:00

@EricStienen : can you give a look to this? Thanks.

**Comment by EricStienen** [comment]
solved at db level

**Comment by damianooldoni** [comment]
Confirmed. Thanks.
