### ISSUE TITLE
Suspect age of birds

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#119]
The are around 50 birds with different values of age (`LeeftijCode`) but same datum (`Datum`) and observer (`WaarnemerNummer`). Some of them are linked to ringing actions and field observations, others to field obs only. Here a table of these birds/obs: [20200316_observations_same-datum_different-age.txt](https://github.com/inbo/cr-birding/files/4338224/20200316_observations_same-datum_different-age.txt)

I think it is worth to solve this at db level. @EricStienen: what do you think about it?

**Comment by EricStienen** [comment]
Indeed an error for 49 birds (different to judge if PULLUS/just 1kJ close to fledging). But not an error for FSAP. The age (LeeftijCode) is the age as noted by the observer, but is not necessarily the right age!!!! The true age can only be derived from  the difference between the age at ringing (rngkl) and the observation date. Similar to Species, the species may be judged wrong by the observer.

**Comment by damianooldoni** [comment]
Thanks to correct the age of those 49 birds! 
About the two obs of FSAP, I leave it as it is, indeed.
