### ISSUE TITLE
update color rings of birds with GPS trackers

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#120]
Since new ringing season, we have to update [map_gps_id_to_color_ring.tsv](https://github.com/inbo/cr-birding/blob/master/data/input/map_gps_id_to_color_ring.tsv). I have found the following new gps codes used in column `Nummer` and should be mapped to their **first** color ring.

Nummer | NummerNieuw
--- | ---
GP202 | FLOG
GP203 | FDOK
GP205 | FHOS
GP104 | FAOS
GP207 | GAOV

@EricStienen: could you provide me such informations? Many thanks!

**Comment by EricStienen** [comment]
All colour rings are new except for FAOS. Its original colour ring was CRAU.

**Comment by damianooldoni** [comment]
Thanks. I will close the issue asap.
