### ISSUE TITLE
Missing longitude direction (E or W)

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#121]
Two observations have no value in `PlaatsLengteRichtingCode` even if field `PlaatsLengteGraden` is not null.

Nummer | KleurringNummer | Datum | PlaatsLengtegraadGraden | PlaatsLengtegraadMinuten | PlaatsLengtegraadSeconden | PlaatsLengtegraadRichtingCode | PlaatsGemeente | PlaatsToponym
--- | --- | --- | --- | --- | --- | --- | --- | ---
93434 | EAAN | 2013-02-19 | 1 | 47 | 11 | | L'ile d' Olonne | [Réserve de Chanteloup](https://goo.gl/maps/69q3Vdumw2M9RL1VA)
81413 | EAHH | 2012-09-21 | 7 | 4 | 45 | | Termunten | [Breebaartpolder](https://goo.gl/maps/K8bAJBJMygMZ9jkn6)

Based on google maps
- Réserve de Chanteloup: **W**est
- Breebaartpolder: **E**ast

`E` or `W` should be added. I can do it while processing the data, but it would be nicer if solved at db level. Can you check it? Thanks in advance.

**Comment by EricStienen** [comment]
Could you please give the code of the colour and the data of these observations Damiano?

**Comment by damianooldoni** [comment]
Sure. Table above updated with `KlerurringNummer` and `Datum`.

**Comment by EricStienen** [comment]
In fact Geert's species but I fixed it for him. Should be OK now.

**Comment by damianooldoni** [comment]
Thanks. Solved.
