### ISSUE TITLE
Update info about birds ringed more than once and birds with GPS tracker

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#123]
Data mapping is done. I am documenting changes in different fields to double check everything and to ease SOVON's data transfer. 

While comparing the values in field `bird_name` I found that the gull Dirk "disappeared". 
Dirk is linked to color ring RTAK in [uvabits_file](https://raw.githubusercontent.com/inbo/bird-tracking/master/data/interim/individuals.csv). The color ring history said: KCAV, RTAK. But RTAK has been changed. Now the sequence is KCAV, GAOK. The metal ring seems not changed: L901928.
This bird has `Nummer` = `GP124` in INBO database (`tblKleurring` table).

@EricStienen : I think the color ring in uvabits file should be updated as well, isn't? Or GAOK is not correct. Could you check it, please? Many thanks.

**Comment by EricStienen** [comment]
indeed Dirk was caught in 2019 and the broken GPS-logger was removed. We also removed the old CR (RTAK) and gave him a new CR (GAOK).

Furthermore I think that the uvabits_file is incomplete. 5 new birds (including Damiano!) are not yet listed in this file. I do not know where I can find the orginal of this file. Do you?

Similary there might be an update needed of the list of birds that were reringed (once or twice). I think that we had such a list for our previous transfer.

**Comment by damianooldoni** [comment]
Thanks. Now it is clear.
Step by step: 
1. the file I linked to you can be modified here: https://github.com/inbo/bird-tracking/blob/master/data/interim/individuals.csv. It is maintained by @peterdesmet, I think.
2. Indeed, the list you provided me for previous transfer was contained in two Excel files. I put them in attachment: 
[controle_Damiano.xlsx](https://github.com/inbo/cr-birding/files/4408646/controle_Damiano.xlsx) and [birds_two_shorthand_not_in_spreadsheet (ES).xlsx](https://github.com/inbo/cr-birding/files/4408622/birds_two_shorthand_not_in_spreadsheet.ES.xlsx). To make things as clean as possible, do not modify the sheets, but please add new rings/birds in new sheets (werkblad) following same structure. Send me by email if you want, or just add them as attachment here (just drag and drop). As you prefer.
.

**Comment by peterdesmet** [comment]
Regarding 1. @EricStienen [that file](https://github.com/inbo/bird-tracking/blob/master/data/interim/individuals.csv) is automatically extracted from the UvA-BiTS database. If you have new metadata for birds, please let me know so I can update it in UvA-BiTS.

**Comment by EricStienen** [comment]
Regarding 1. @peterdesmet  the UvaBits file was updated a few days ago by Hans Matheve. So you do not have to add data and @damianooldoni could you check if the new birds are added in the csv now?

**Comment by EricStienen** [comment]
regarding 1. just to be sure @peterdesmet. These are the new logger birds caught in 2019 and 2020. I am not sure if Hans added the Herring Gulls in the he UvA-BiTS database. Can you check this.

[GPS_BIRDS 2019-2020.xlsx](https://github.com/inbo/cr-birding/files/4487815/GPS_BIRDS.2019-2020.xlsx)

**Comment by peterdesmet** [comment]
I just checked and that info was added to the database by Hans on April 10 👏. Just had to make two minor corrections. Damiano, the individuals data is now updated.

@EricStienen, I'll send a separate issue about gull tony in the bird-tracking repo

**Comment by damianooldoni** [comment]
Thanks @peterdesmet! I will import it again.

@EricStienen: when you send me the updated info about [point 2 above](https://github.com/inbo/cr-birding/issues/123#issuecomment-606564665) I can finalize the export process.

**Comment by damianooldoni** [comment]
This issue has been solved and can be closed.
