### ISSUE TITLE
multiple actions veld/meweg for bird CUAT

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#124]
There is one bird only where action `meweg` (coupled with action `veld`) is assigned to two observations. This make my mapping wrong as it seems the bird lost its metal ring twice which is not the case as no observation with action `vang` has been recorded in between, so bird didn't get a new metal ring in between.

Do we agree that `meweg` is assigned only to the first observation where it is noticed that the metal ring is missing? So could you remove the action `meweg` linked to the latest observation (2019-06-28) here below? Thanks.

Datum | KleurringNummer | PlaatsGemeente | WaarnemerNummer
--- | -- | --- | ---
2016-05-09 | CUAT | Zeebrugge | 164
2019-06-28 | CUAT | Blankenberge | 1600

**Comment by EricStienen** [comment]
solved at DB level

**Comment by damianooldoni** [comment]
Indeed, thanks. I close the issue.
