### ISSUE TITLE
bird reference as unique identifier

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#128]
From email of @JeroenNienhuis:

> Is `bird_reference` nu wel een unieke identifier of een ander rijnummer. Eventueel kun je ook ringcentrale en ringnummer van de eerste metalen ring die een vogel ooit heeft gekregen aan elkaar plekken als identifier. Bij vogels zonder metalen ring kun je de kleurcode gebruiken. Een eenmaal gekozen identifier moet niet meer veranderen (ook niet als de vogel later alsnog een metalen ring krijgt).

**Comment by damianooldoni** [comment]
@JeroenNienhuis: the answer is yes: **within** the data export (users, birds and obs data) I provided you on 30th April the field `bird_reference` is an unique identifier. However, the values of `bird_reference` in these data are not the same ones as in the data of 2019. For this reason I added the column `bird_reference_2019` thinking it could help you in comparing old data (from 2019 export) with new data.
If it generates confusion I am more than happy to remove it from final export :+1: 
Or do you prefer having the very same bird reference as given in 2019 where possible, i.e. all birds present in 2019 data?

**Comment by JeroenNienhuis** [comment]
A new and unique identifier is good. I need the column with the 2019 ID to update the previous data.

**Comment by damianooldoni** [comment]
Thanks @JeroenNienhuis. By the way, I found better for me as well to reuse `bird_reference` values from 2019 where possible (https://github.com/inbo/cr-birding/commit/b064ed2634e6aacef79310e927e3a1e440d7ba6e). This will ease your work as well.
