### ISSUE TITLE
Metal rings assigned to multiple birds

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#131]
While mapping data export of 2019 with new data I discovered 67 metal rings (`MetaalringNummer`) assigned to multiple birds (`Nummer`). List here below (or download it from [metalrings_multiple_birds.txt](https://github.com/inbo/cr-birding/files/4799730/metalrings_multiple_birds.txt)).
@EricStienen: should we do something about it or do we provide data to SOVON like that? Just to know. Thanks.

MetaalringNummer | color_rings
--- | ---
B4682 | KNB, KNC
H106557 | BAAD, BRAL
H136813 | FWAH, BGAT
H145995 | CVAS, CVAW
H152993 | CPAG, HSOW
H900737 | PTAY, MFAS
H902097 | ZUAB, ZTAV
H903118 | ZCAY, ZCAV
H903197 | YAAF, YDAY
H905124 | CZOP, CUOH
H905143 | CBOZ, CPOM
H905182 | ZNAV, ZMAS
H907586 | BABU, CBOA
H907617 | FUOG, FKON
H907728 | CVOV, CVOC
H907773 | CDOH, CLOG
H907836 | PTAB, FWOP
H907863 | ZMAU, ZNAU
H908140 | ACBC, HROG
H908162 | DLOV, ABBJ
H908219 | ABBT, HHOW
H908242 | HAOL, HJOW
H908248 | HROF, ABBK
H908856 | ACBF, HGOL
H908889 | ABBV, HPOJ
H908894 | ABBW, HSOM
H908942 | HZOH, ABBS
H908983 | HCOU, ACBE
H908987 | ABBX, HLOG
H909710 | FBOM, FPOJ
L907262 | HMAU, AABJ
L907456 | GSAG, GSAF
L909162 | HRAA, HRAX
L909702 | ALOB, LPAV
L909776 | NDAX, MNAM
L916148 | RKAB, RJAJ
L916272 | MLAR, SLAB
L916660 | TJAV, HBAW
L920531 | RUAN, RVAG
L925380 | BVOR, BDOU
L925539 | BWOL, AROS
L925547 | APOA, AHOA
L925837 | BLOB, BTOS, BNOF, BLOG
L925917 | APOZ, ASOH
L925996 | ASON, CDOV
L926132 | GTOT, ACBG
L926218 | DNOV, DUOU
L926299 | BABW, DLOR
L926313 | GDOW, HHOJ
L926365 | GKOS, ABBI
L926372 | ABBH, GJON
L929551 | GNOK, ABBP
L929552 | GNOZ, ACBM
L929554 | GSOL, GSOJ
L929564 | GSON, ABBO
L929571 | GSOT, ABBN
L929627 | ABBZ, GHOC
L929696 | ACBA, HUOS
L929738 | GZOH, ACBP
L929740 | GZOV, ACBQ
L929751 | ABBQ, GZOC
L929753 | ACBB, GZOB
L929765 | ABBR, GHOU
L929777 | GHOR, ACBI, ACBR
L929790 | GNOB, ACBK
L929791 | GNON, ACBL
L929793 | ABBU, GCOD

**Comment by EricStienen** [comment]
That is a lot of work to sort this out. I did sent the list to Marc. Hopefully he will find some time for this soon.

**Comment by damianooldoni** [comment]
From e-mail of @EricStienen:

 > even ter verduidelijking 

Alle dubbele metaalringen van onze grote meeuwen zouden er bij een volgende controle uit moeten zijn, tenminste wanneer de fictieve kleurrringen die een B op de derde positie er eerst uit zijn gegooid.

**Comment by damianooldoni** [comment]
I have just checked this. After removing rings with B at third position, I still found 17 metal rings assigned to multiple birds  (`Nummer`):

MetaalringNummer | rings
-- | --
H136813 | FWAH,BGAT
H152993 | CPAG,HSOW
H902099 | ZUAB,ZVAB
H907836 | PTAB,FWOP
H908482 | LTOF,LROC
H908538 | HMOZ,HLOD
L909161 | HRAA,HRAW
L909702 | ALOB,LPAV
L916148 | RKAB,RJAJ
L920170 | KNOM,KLOL
L930062 | KLOF,KZOF
L930083 | KSOF,KMOU
L930109 | KUOD,KTOK
L930114 | KNON,KROS
L930136 | KDOU,KTOU
L930155 | KHOS,KHOJ

@EricStienen : could somebody check this?

**Comment by EricStienen** [comment]
Damiano, could you check this again. I think that these problems are now all solved at db-level. But if there is still one or two eft, please let me know.

**Comment by damianooldoni** [comment]
Thanks @EricStienen for such a fast action!
I find now only two duplicates, where the first one is probably not one of our rings?

MetaalringNummer | Nummer
-- | --
B4682 | KNB, KNC
L916147 | RKAA, RJAJ

**Comment by EricStienen** [comment]
first one is indeed not ours. second is solved at db level.

**Comment by damianooldoni** [comment]
Confirmed. Issue can be closed. :partying_face:
