### ISSUE TITLE
We lost Dirk, the gull

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#132]
While comparing data of 2019 with actual data, I see that we "lost" the bird called _Dirk_. In the file with data about [bird-tracking individuals at line 120](https://github.com/inbo/bird-tracking/blob/master/data/interim/individuals.csv#L120) you can see it is linked to color ring `RTAK`, which is not present anymore in `tblKelurring` table.
@EricStienen : I wonder whether it's on purpose or not. Just a question. Thanks.

**Comment by damianooldoni** [comment]
It seems also that this gull wore previously the ring `KCAV`. And by the information I have now, `KCAV` has been replaced by ring `GAOK` on 2019-06-05.
In data of 2019 the ring `KCAV` has been replaced by ring `RTAK` on 2016-05-26.
So, I suspect this can be a possible new triplet with "intermediary" ring `RTAK`.

**Comment by EricStienen** [comment]
you are completely right Damiano. A new triplet indeed.

**Comment by damianooldoni** [comment]
This is one of the triplets found by @EricStienen. From his email on Sept. 9:

> Ik heb 3 extra tripletten kunnen vinden namelijk
>1. KMAV geringd op 27/5/2008 
   31/05/2012 KMAV -> UMAR
   25/05/2019 UMAR -> DAOW
>2. KCAV geringd op 23/05/2008
    26/05/2016 KCAV -> RTAK
    05/06/2019 RTAK -> GAOK
>3. BCAV geringd op 29/07/1999
   01/06/2009 BCAV -> LMAA
   22/05/2020 LMAA -> KDOP
