### ISSUE TITLE
Bird not linked to any observation

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#134]
I found a bird not linked to any observation:

Nummer | NummerNieuw | NummerDesc |EuringCode
--- | --- | --- | ---
KOAZ | KOAZ | K.OAZ | 5910

@EricStienen: could you please give a look?

**Comment by EricStienen** [comment]
solved at DB level

**Comment by damianooldoni** [comment]
Confirmed. Thanks. I close the issue.
