### ISSUE TITLE
Field observation date after bird death date

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#135]
I found a field observation (observation linked to action `veld`) of a bird which is linked to an earlier  `dood` observation (2020-07-22):

Nummer | KleurringCode | Datum
--- | --- | ---
154081 | KMOR | 2020-08-13

@EricStienen: could you please give a look? Thanks.

**Comment by EricStienen** [comment]
solved at DB-level

**Comment by damianooldoni** [comment]
Indeed, I confirm it. Issue can be closed. Thanks!
