### ISSUE TITLE
birds in tblKleurring not linked to any action rngkl

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#15]
While trying to retrieve the date of ringing, I found that these four birds are not linked to any `KleurringNummer` in tblWaarneming with a `rngkl` asociated action in `tblWaarnemingAktie`:

Nummer | NummerNieuw | NummerDesc | Plaats | RingKleurCode | InscriptieKleurCode | EuringCode | GeslachtCode | MetaalringNummer | MetaalringLandCode
--- | --- | --- | --- | --- | --- | --- | --- | --- | ---
BBS | BBS | BBS | RL | G | W | zzz | O | B5234 | 
EAAX | EAAX | EAAX | LU | W | Z | zz | V | E999999	| 
EAKM | EAKM | EAKM | LU | W | Z | 04560 | O | E922412 | BE
EAKE | EAKE | EAKE | LU | W | Z | 04560 | O | E922405 | BE

Is this normal? Have they been ringed by somebody else? Should I add an empty value then? 
Eric, Marc: your advice is welcome :rescue_worker_helmet:

**Comment by damianooldoni** [comment]
Eric:
> Dat zijn aalscholvers en kluten. Niet mijn projecten dus. Ik stuur het even door naar Geert en Filiep, zodat zij dat kunnen aanpassen in de database.

**Comment by damianooldoni** [comment]
Some more information: 
we speak about cormorants-shags and avocets linked to 12 observations in total. Here below a preview where field `AktieCode` from `tblWaarnemingAktie` has been added to the information coming from `tblWaarneming` for a better understanding.

Nummer | Datum | KleurringNummer | AktieCode | EuringCode | LeeftijdCode
--- | --- | --- | --- | --- | --- 
95246 | 2013-05-02 | BBS | veld | zzz | PU	
99123 | 2013-09-01 | BBS | dood | zzz | AD	
100087 | 2014-04-01 | EAAX | veld | zz | AD	
107184 | 2015-04-17 | EAAX | veld | 04560 | AD	
120383 | 2017-04-28 | EAAX | veld | 04560 | AD	
60237 | 2010-09-10 | EAKE | veld | 04560 | J1	
77946 | 2012-02-24 | EAKE | veld | 04560 | I3	
77945 | 2012-02-21 | EAKE | veld | 04560 | I3	
79900 | 2011-07-14 | EAKE | veld | 04560 | I2	
60235 | 2010-08-24	 | EAKM | veld | 04560 | J1
60238 | 2010-08-19 | EAKM | veld | 04560 | J1	
117945 | 2011-07-05 | EAKM | veld | 04560 | AD

**Comment by damianooldoni** [comment]
Answer of Geert:
> EAAX, EAKE en EAKM heb ik in orde gebracht.

**Comment by damianooldoni** [comment]
I confirm it. There is still no action `rngkl`coupled to bird `BBS`. The only obs related to this bird are the following ones:

Nummer | Datum | KleurringNummer | AktieCode | EuringCode | LeeftijdCode
--- | --- | --- | --- | --- | --- 
95246 | 2013-05-02 | BBS | veld | zzz | PU	
99123 | 2013-09-01 | BBS | dood | zzz | AD	

I will leave the field empty for this bird until I get news about.

**Comment by damianooldoni** [comment]
Answer of Filiep:
> ik heb `BBS` aangepast.

I confirm it. The observation with nummer 95246 doesn't point to action code `veld` anymore, but to actions: `rngkl` and `rngme`. 

Issue solved.

**Comment by damianooldoni** [comment]
The birds ringed with rings KCOB and LZOC are not linked to any action `rgnkl`. They are both linked to only one `veld` observation:

Nummer | Datum | EuringCode | LeeftijdCode | KleurringNummer
-- | -- | -- | -- | --
152694 | 2020-08-11 | 5910 | J1 | KCOB
152793 | 2020-08-17 | 5920 | J1 | LZOC

@EricStienen: could you please give a look into this? Should be action `veld` be changed to `rngkl`? Or should be added a new observation linked to action `rgnkl`? Or ...?

**Comment by EricStienen** [comment]
solved at db level

**Comment by damianooldoni** [comment]
Checked. Indeed, solved.

**Comment by damianooldoni** [comment]
I have to open this issue again as I automatically detected a new anomaly.

There are no observations of the bird with ring CPAG linked to action `rngkl`.

Here below a short chronology:

KleurringNummer | Nummer | Datum | Opmerking | veld | rngme | klweg | ziek
-- | -- | -- | -- | -- | -- | -- | --
CPAG | 145867 | 2008-07-14 | krijgt ook een kleurring (veldgegevens zoek, niet zeker welke) en bovendien is de kleurring niet meer aanwezig wanneer in 2019 HSOW wordt aangebracht. |  | rngme |  | 
CPAG | 42855 | 2008-12-24 |  | veld |  |  | 
CPAG | 44319 | 2009-02-03 | CPA.G | veld |  |  | 
... | ... | ... |  | veld |  |  | 
CPAG | 132935 | 2018-09-07 | niet zeker van de C | veld |  |  | 
CPAG | 144823 | 2019-09-09 | had reeds metaal, krijgt nu HSOWgelost |  |  | klweg | ziek

@EricStienen: could somebody check this? Thanks.

**Comment by EricStienen** [comment]
solved at db level

**Comment by damianooldoni** [comment]
Confirmed. Thanks.
