### ISSUE TITLE
retrieve date of applying new ring

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#22]
Mapping of bird short hand (#11) is almost done, I think. Now, the very last effort for a part of this mapping which I would like to discuss separately.
 
Based on the nice example of @EricStienen (https://github.com/inbo/sovon/issues/11#issuecomment-426326332) and the mapping we all agree here below:

bird_reference | bird_shorthand | bird_date_begin | bird_date_end | bird_rings_changed
--- | --- | --- | --- | ---
100 | AMAS | 02-05-2016 (fictief) | 01-07-2018 |                                    
100 | C.ZAD | 01-07-2018 | | 1

we need to retrieve the date when the ring has been changed (`01-07-2018` in our example). This is important because 396 birds have been ringed twice. So, the question is the following:
the action of applying a new ring is linked to 
1. action `gevangen op nest` (AktieCode `vang`)? 
2. a combination of actions?

I suppose option 1 is correct because it holds true for 379 birds, but the remaining 17 birds are linked to two actions `vang`. @EricStienen: can you give me a hint? Thanks a lot.

**Comment by EricStienen** [comment]
not easy. Some birds have action code "vang", while the old ring was not removed and some birds were even reringed twice. I am afraid that we must do this partly by hand. Can you provide a list with birds that were caught (vang) & a list of birds that have two differnt bird_shorthand. We we can than have a look at this problem.

**Comment by damianooldoni** [comment]
Sure, @EricStienen. you can find three files in folder `.data\interim\` of this repository. 
Description:
1. `birds_vang_obs_info.csv` contains all information related to ALL birds which have been caught at nest (`vang`) or caught otherwise (`vangl`). I added also datum (`raw_Datum`) and action code (`raw_AktieCode`: `vang` or `vangl`). I hope it will ease your work.
2. `birds_two_shorthand_no_vang.csv` contains information about birds with two different color rings (`raw_Nummer` and `raw_NummerNieuw`) which have never been caught (no `vang` action found).
3. `birds_two_shorthand_vang.csv` contains information about birds with two different color rings (`raw_Nummer` and `raw_NummerNieuw`) which have been caught at least once.

The columns of all files are the same as in our database, except the prefix `raw_`, which I automatically add at the beginning of the mapping script. 
Just let me know if you want extra specific information or anything else I can do for helping to solve this issue.

**Comment by peterdesmet** [comment]
Link to the files @damianooldoni mentions: https://github.com/inbo/sovon/tree/master/data/interim

**Comment by damianooldoni** [comment]
Eric's answer: 

I checked all rings in the files. You find the results in attachment: [controle Damiano.xlsx](https://github.com/inbo/sovon/files/2533432/controle.Damiano.xlsx). There are ,however, a few difficulties.

In the file you find a column called `vervang` and you see various colors. 

The WHITE lines with `vervang` = `YES` mean that the colour ring was replaced at `date = raw_Datum`, the old code was `raw_Nummer` and the new code is `raw_NummerNieuw`

The RED lines with `vervang` = `NO` mean that the bird was caught but the ring was not replaced.

The PINK lines are two special cases that I added to the file. These birds were not caught, but they were sick and their ring was replaced in the VOC or elsewhere. The old code was `raw_Nummer` and the new code is `raw_NummerNieuw`.

The YELLOW lines are all birds that carry a GPS logger. When they were caught on the nest to tag them with a gps, the old colourring was replaced by a new one. However the old ring can not be found in the column raw_Nummer. This column refers to the GPSnr. I added the old colour rings in an extra column. Maybe we should use these as old CR-number and add the fact that they wear a GPS in an additional column.

The DARK BLUE lines are also birds that carry a GPS logger. However, their colourring was not replaced when they were tagged with a gps.  Their old colourring = `raw_NummerNieuw`. Also here extra info of their GPS should be added in a new column.

The ORANGE lines are also birds that carry a GPS logger. They were caught twice and in most cases their colourring was replaced twice. Except for two special cases (in brown) that were caught twice but the cr-ring was only replaced once (in orange). 

A very special case in LIGHT GREEN. That was caught with a colour ring and a second colour ring was added.

And finally from line 318 onwards, some birds that were actually caught on the nest and in most cases received a new colour ring, but that were previously not included in our database with actiecode `
vang`. Now they are.

Is that clear and helpful?

**Comment by damianooldoni** [comment]
While working on spreadsheet you gave me, I found 76 rows in `tblKleurring` with `Nummer` different from `NummerNieuw` and not mentioned in spreadsheet. Do you think is possible to do the same nice mapping you did for the other ones? It will help a lot to know the date of applying the new ring. Thanks.
File: [birds_two_shorthand_not_in_spreadsheet.txt](https://github.com/inbo/sovon/files/2555179/birds_two_shorthand_not_in_spreadsheet.txt).

**Comment by damianooldoni** [comment]
Update: Eric provided the needed mapping in file [controle_Damiano.xlsx](https://github.com/inbo/sovon/blob/master/data/input/controle_Damiano.xlsx).
Thanks.

**Comment by damianooldoni** [comment]
I can happily conclude that the mapping of all rings is succeeded. All rings have the right date:
```r
> crbirding_birds %>%
+     mutate(date_is_present = !is.na(bird_date_begin)) %>%
+     group_by(date_is_present) %>%
+     count()
# A tibble: 1 x 2
# Groups:   date_is_present [1]
  date_is_present     n
  <lgl>           <int>
1 TRUE             9946
```

This important issue can then be closed.
