### ISSUE TITLE
Handle information about GPS logger

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#23]
I report from https://github.com/inbo/sovon/issues/22#issuecomment-434605449:
> The YELLOW lines are all birds that carry a GPS logger. When they were caught on the nest to tag them with a gps, the old colourring was replaced by a new one. However the old ring can not be found in the column raw_Nummer. This column refers to the GPSnr. I added the old colour rings in an extra column. Maybe we should use these as old CR-number and add the fact that they wear a GPS in an additional column.

> The DARK BLUE lines are also birds that carry a GPS logger. However, their colourring was not replaced when they were tagged with a gps. Their old colourring = raw_NummerNieuw. Also here extra info of their GPS should be added in a new column.

The fact that a bird carries a GPS logger can be easily saved in `bird_notes`, e.g. by adding the fixed string `"gps_tagged"` or if you want to be more specific `"uvabits_gps_tagged"`. 
@EricStienen : what do you think about?

**Comment by EricStienen** [comment]
Fine for me if for all GPS-tagged birds a string is added. I would prefer "gps_tagged + GPS number". The latter can be found in the column raw_Nummer. In case of the GPS-birds that is not the colourring code but a dummy variable showing the number of the GPS noted as GPS** or GP**.

**Comment by peterdesmet** [comment]
@EricStienen, I see why it could be useful to directly include the GPS number, but then we need to maintain that information in two places. For the GPS tracking network and here. I would avoid that and only indicate here if a gull has been tagged. Which tag it was can be easily looked up in the GPS network (e.g. your Excel, UvA-BiTS or an [UvA-BiTS export](https://github.com/inbo/bird-tracking/blob/master/data/interim/individuals.csv))

**Comment by EricStienen** [comment]
In fact the number is not very important, but inclusion of the name of the bird in the notes would be extremely handy. Looking it up in a seperate file each time a cr is read would be very time consuming. A 
negligible amount of effort would save a lot of effort afterwards.

**Comment by damianooldoni** [comment]
Thanks Eric for your feedback. I implemented it by adding *uvabits_gps_tagged.* + *name*. For example, GP130 gets `'uvabits_gps_tagged.John.'` in column `bird_notes`.

**Comment by peterdesmet** [comment]
Would suggest space pipe space: `uvabits_gps_tag | John`
