### ISSUE TITLE
MetaalringNummer in tblKleurring not matching MetaalringNummer in tblWaarneming

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#24]
There are 77 metal rings in `tblKleurring` which do not match the metal ring filled in `tblWaarneming`.

Nummer (tblKleurring) = KleurringNummer (tblWaarneming) | NummerNieuw (tblKleurring) | MetaalringNummer (tblKleurring) | MetaalringNummer (tblWaarneming)
--- | --- | --- | --- 
AAAA | CYAA | H159513 | H99573	
AAAR | KPAU | H152230 | H99580	
AAAT | KJAB | L909219 | L85125	
AAAW | AAAW | 5302074 | 5.302.074	
ACAG | GVAF | L906681 | L89047
AFAB | LBAW | L907345 | L89419	
AFAR | KGAN | L909671 | L89035	
AFAS | LBAG | L909989 | L85114	
AFAU | FAAB | H145595 | H99543	
AGAG | LCAU | L909946 | L89435	
AHAP | DLAR | H146407 | L83487	
AHAS | LGAJ | L911709 | L89449	
AJAA | KYAC | L909965 | L89055	
AJAD | GDAB | L906732 | L89404	
AJAJ | GLAD | L906743 | L89060
AJAP | KRAL | H146476 | H106513	
AJAT | STAW | H901951 | H99547	
AJAZ | CTAP | H153881 | H99569	
AKAB | KSAN | H152241 | H106516	
AKAU | NGAB | L913152 | L89066	
ALAL | GHAG | L907017 | L89072	
AMAD | GFAR | L907009 | L83481	
AMAL | LBAH | L909994 | L89080	
AMAN | CTAG | H153875 | H106538	
AMAS | CZAD | H136755 | H99535
ANAN | HVAC | L909616 | L89090	
ASAF | GDAC | H152148 | H99549	
ASAG | KAAT | L907232 | L89117	
ASAK | KMAP | L907409 | L89120	
ASAP | SZAT | H902297 | L89122	
ASAV | PMAV | H901760 | H106600	
ASAX | KCAN | L909270 | L89124	
ASAY | HWAT | L909644 | L89125	
ATAN | YYAN | H903059 | H106612	
AUAB | KLAM | H146487 | H99635
AUAP | KGAR | L909674 | L89134	
AVAD | UTAL | L914601 | L89137	
AVAP | KSAP | H152242 | H99654	
AYAK | KRAD | H146480 | H106685	
AZAK | DHAA | L902147 | K6090	
BBAT | GHAB | L907013 | L89199	
BCAD | GJAV | L907008 | L89201	
BCAV | LMAA | L909920 | L89215	
BDAD | GMAA | L906637 | L89224	
BFAT | KRAT | H146470 | H106637
BHAK | KPAV | H152231 | H99623	
BHAR | CWAC | H159511 | H99628	
BHAW | URAA | L914607 | L89377	
BJAA | HWAF | L909636 | L85151	
BJAY | GJAY | L907007 | L85160	
BKAB | CZAK | H153898 | H99678	
BKAG | GHAM | L907022 | H99680	
BLAD | HWAJ | L909631 | L85171	
BLAH | KSAF | L909268 | L85174	
BLAR | KKAB | L909682 | L85181
BLAY | BLAY | EA676412 | L85187	
BMAN | CZAX | L909903 | L85194	
BNAH | BNAH | L909611 | L89460	
BPAK | WE | 5434911 | L89483	
BRAX | KRAV | H146485 | H106667	
BRAZ | GFAT | H145698 | H106669	
BSAL | UPAR | L914621 | L89160	
BSAX | KBAU | L907216 | L89166	
BSAY | TSAK | L912663 | L89243	
BTAF | PJAN | L914501 | L89171
BUAJ | GMAF | L907001 | L89246	
BWAK | GZAX | L906541 | L92035	
BYAM | CZAJ | H161455 | H112326	
BZAC | KRAC | H146474 | H112398	
CAAM | CNAA | 6166723 | H112348	
BRAD | BRAD | 5360351 | H106651	
BRAF | FUAJ | H136842 | H106652

There are also many missing values in field `metaalringNummer` of `rblWaarneming`. For example, for KleurringNummer = `AAAA` we have 51 observations with empty value in field `MetaalringNummer` and 1 with `MetaalringNummer` equal to `H99573` (in first row of table above).
@EricStienen : If you can assure me that the metal ring information in `tblKleurring` is correct, than I use it as ring number and I ignore the information in `tblWaarneming`. If this is not the case, could you please help me to know which should I take? Thanks a lot.

**Comment by EricStienen** [comment]
only the metal ring information in tblKleurring is correct!!!

**Comment by damianooldoni** [comment]
Issue can be closed.
