### ISSUE TITLE
sequence of dates of ringing bird GPS11 aka URAL

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#26]
@EricStienen : you wrote the following remark in spreadsheet about bird with Nummer equal to GPS11:

> was PR3, wordt DHAZ en in 2013 URAL met GPS, waarneming toegevoegd aan DB

Do you know also the dates of ringing? I can find this info in database:

1. `rngkl` at 1997-06-28: datum of applying PR3 ring?
2. `rngme` at 2006-05-26: did the ringer maybe applied color ring DHAZ while applying metallic ring?
3. `vang` at 2013-05-30: URAL ring applied as you mentioned

It seems to me the most logical sequence of dates, but I would like you confirm this. 
Thanks!

**Comment by EricStienen** [comment]
yes!
