### ISSUE TITLE
sequence of dates of ringing GPS23 aka UAAM

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#27]
Isseu similar to #26.

From your spreadsheet, the series of rings of bird with `Nummer` GPS23 and `NummerNieuw` UAAM  is the following:
TY2 -> GMAJ -> UAAM (in 2013)

For this bird I find these possible actions/dates:

AktieCode | Datum
--- | --- 
rngkl | 1997-07-05
rngme | 2007-06-06
vang | 2007-06-06
vang | 2013-06-10

Very likely:
1. `rngkl` on 1997-07-05: date of applying TY2
2. `rngme` and `vang` on 2007-06-06: did the ringer maybe applied color ring GMAJ while applying metallic ring too?
3. vang on 2013-06-10: UAAM ring applied as you mentioned

@EricStienen , could you please confirm this time sequence?

**Comment by EricStienen** [comment]
yes! On 2007_06_06 the bird was caught on the nest, the old CR TY2 was changed for a new CR GMAJ & a metal ring was added.
