### ISSUE TITLE
sequence of dates of ringing GPS24 aka UPAC

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#28]
Similarly to issue #27 , this is your sequence for bird with `Nummer `GPS24` and `NummerNieuw` UPAC:
RT0 -> DGAH -> UPAC. In remarks you wrote:
> was RT0, nu DGAH in 2011 DGAH, toegevoegd aan DB

I have found the next sequence of actions/dates:

AktieCode | Datum
--- | ---
rngkl | 1998-07-08
rngme | 2006-05-17
vang | 2006-05-17
vang | 2013-06-11

I think that your 2011 is a typo, you meant 20**13**-06-**11**. I see also date 6/7/2006 in field `raw_Datum` (line 288 of spreadsheet) which I cannot couple to any date above (year 2006 is still ok). 

Based on table above, I would opt for the following quite logical sequence:
1. `rngkl` on 1998-07-08: date of applying RT0 
2. `vang`-`rngme` on 2006-05-17: date of applying DGAH
3. `vang` on 2013-06-11: date of applying UPAC

@EricStienen : could you please confirm?

**Comment by damianooldoni** [comment]
I found the bug. In the comment of the spreadsheet [controle_Damiano.xlsx](https://github.com/inbo/sovon/blob/master/data/input/controle_Damiano.xlsx) at line 288:
> was RT0, nu DGAH in 2011 DGAH, toegevoegd aan DB

Actually the very first ring was not `RT0` but `RTO`. It's `RTO` the ring linked to GPS tracker GPS24. 
So, the sequence of color rings is:

RTO -> DGAH -> UPAC (UPA.C). 

Now I understand why I couldn't find any `vang` action in database for `RTO` (aka GPS24) with date 2006-07-06 as mentioned in spreadsheet: this date refers to a `vang` action for bird `**RT0**`, not `**RTO**`.

So, for me is this issue solved: I will use the temporal sequence as mentioned above:
1. `rngkl` on 1998-07-08: date of applying RT0 
2. `vang`-`rngme` on 2006-05-17: date of applying DGAH and metal ring
3. `vang` on 2013-06-11: date of applying UPAC
 
@EricStienen : I would like to hear your final words on this issue before closing it. Thanks.

**Comment by EricStienen** [comment]
yes your interpretation is right!

**Comment by damianooldoni** [comment]
Thanks. We can then close this issue.
