### ISSUE TITLE
Filling SOVON reserved field bird_name

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#29]
In SOVON spreadsheet there is a column called `bird_name`, labelled by Lisenka as a field to be populated by SOVON. 

As it came out while discussing issue #23, we have some bird names and I put it in `column `bird_notes. However, it would be nice if we can add the names we know in field `bird_name`. 

I asked to Lisenka about it.

**Comment by peterdesmet** [comment]
👍 Good, adding it in a proper db field
Would be much better.

**Comment by damianooldoni** [comment]
Answer of Lisenka:
> De kolom `bird_name` is optioneel, je kunt hier de “nickname” van een vogel invullen. Meestal krijgen vogels geen naam, dus om verwarring te voorkomen is deze niet gearceerd.
Mochten jullie vogels met namen hebben, dan kun je deze gerust daar invullen.

So, we have permission to add the name in the right field. I will change it in the mapping.
