### ISSUE TITLE
sequence of dates of ringing GPS28 aka CZOZ

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#30]
From line 294-295 from [your first spreadsheet](https://github.com/inbo/sovon/blob/master/data/input/controle_Damiano.xlsx):

raw_Nummer | raw_NummerNieuw | raw_Datum | vevang | remarks
--- | --- | --- | --- | ---
GPS28 | CZOZ | **2017**-06-09 | TWICE | was MKAU, nu ZVAU
GPS28 |CZOZ | **2014**-05-23 | TWICE | was ZVAU, nu CZOZ

By your remarks and taking account that CZOZ is the `NummerNieuw`, i.e. the most recent ring, I think the dates in `raw_Datum` have to be swapped. I think the right sequence of rings is:
MKAU -> ZVAU -> CZOZ

@EricStienen : could you confirm?

**Comment by EricStienen** [comment]
confirmed!

MKAU -> ZVAU -> CZOZ is the right sequence
