### ISSUE TITLE
Birds in bird tracking individuals text file not found in our database

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#31]
While mapping the bird name as decided in https://github.com/inbo/sovon/issues/29#issuecomment-447770771, I found that the color ring of some birds in [individuals.csv](https://raw.githubusercontent.com/inbo/bird-tracking/master/data/interim/individuals.csv) are not in our database. 
The most similar to our color rings are the following:
1. the oystercatchers `EARN`, `EARA`, `EARE`,  `EARP`, `EARK` 
2. the gull `DROD`

The others are quite strange: `8K (b)`, `8C (b)`, ... containing spaces and brackets.
@peterdesmet: is it possible they are not "our" birds?

**Comment by peterdesmet** [comment]
@EricStienen is it possible that some of the tracked gulls/oystercatchers are NOT in the “kleuringendatabase”?

**Comment by damianooldoni** [comment]
I found 4 other birds in [individuals.csv](https://raw.githubusercontent.com/inbo/bird-tracking/master/data/interim/individuals.csv) not present in the "kleurringdatabase":

individual_id | ring_number | individual_remarks | colour_ring | species_latin_name
--- | --- | --- | --- | ---
268 | 5446465 | William |   | Circus aeruginosus
158 | 5336455 | Kjell |   | Circus aeruginosus
836 | 5325667 | Roelof |   | Circus aeruginosus
1321 | 5327085 | Job |   | Circus aeruginosus

I tried searching by metal ring (`ring_number`) but I couldn't find them. 
@EricStienen : any idea?

**Comment by EricStienen** [comment]
My knowledge is restricted to the gulls. This is a question for Filip Tjoleyn.

**Comment by damianooldoni** [comment]
Thanks @EricStienen : I will contact Filip then.

**Comment by damianooldoni** [comment]
Filip Tjoleyn contacted: he confirmed that these birds are not in color ring database as they don't have a color ring actually.

**Comment by damianooldoni** [comment]
This "enhancement" will not occur. Definitely not a problem.
