### ISSUE TITLE
FHOV: date of applying ring not found 

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#32]
The ring SUAV has been applied on 2011-07-13 and it has been changed to FHOV at a certain moment which I cannot find.
Searching all observations/actions linked to SUAV/FHOV (EuringCode: 05920) I get one `rngkl` action (applying the first ring, SUAV) and one `rngme`(applying metallic ring) and 45 field observations (`veld`). In the table below a preview, only very first and very last observations included.

AktieCode | Datum
--- | ---
2011-07-13 | rngkl
2011-07-13 | rngme
2011-08-25 | veld
2011-09-01 | veld
2011-09-08 | veld
... | veld
2018-04-09 | veld
2018-04-09 | veld
2018-12-02 | veld

So, I don't find any clue about the date of applying the ring FHOV. @EricStienen : can you help me?

**Comment by EricStienen** [comment]
The ring FHOV was applied at 26/04/2018 when the action code reads "ziek".

**Comment by damianooldoni** [comment]
Confirmed. Issue can be closed. Thanks.
