### ISSUE TITLE
absence of action rngme for some birds

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#33]
The following 100 birds have a metal ring but I didn't find any action `rngme` linked to them. Should I assume that the metal ring has been applied while applying the (first) color ring (action `rngkl`)? In any case, it would be nice to add an observation with action `rngme` for these metal rings. Here below a table with the needed information from database table `tblKleurring`:

Nummer | NummerNieuw | NummerDesc | MetaalringNummer
--- | --- | --- | --- 
KPAJ | KPAJ | KP.AJ | H152221	
BBH | BBH | BBH | B5134	
BBJ | BBJ | BBJ | B5135	
BBK | BBK | BBK | B3136	
BBL | BBL | BBL | B3137	
BBM | BBM | BBM | B3138	
BBN | BBN | BBN | B5140	
BBP | BBP | BBP | B5231	
BBR | BBR | BBR | B5233	
BBU | BBU | BBU | B4618
BBT | BBT | BBT | B4619	
C1 | C1 | C1 | H160979	
C2 | C2 | C2 | H160980	
C3 | C3 | C3 | H160981	
BBW | BBW | BBW | B4621	
BBV | BBV | BBV | B4620	
BBX | BBX | BBX | B4622	
BBY | BBY | BBY | B4623	
BCC | BCC | BCC | B4624	
BCF | BCF | BCF | B4625
BCE | BCE | BCE | B4626	
BBZ | BBZ | BBZ | B4627	
BCA | BCA | BCA | B4628	
BCB | BCB | BCB | B4629	
D1 | D1 | D1 | H167426	
DL | DL | DL | H167439	
KVL | KVL | KVL | B4470	
A1 | A1 | A1 | H160614	
A2 | A2 | A2 | H164420	
A4 | A4 | A4 | H164421
A6 | A6 | A6 | H164422	
A7 | A7 | A7 | H164423	
A9 | A9 | A9 | H164424	
AD | AD | AD | H164411	
AE | AE | AE | H164412	
AH | AH | AH | H164415	
AJ | AJ | AJ | H164416	
AK | AK | AK | H164413	
AL | AL | AL | H164414	
AS | AS | AS | H164417
AT | AT | AT | H164418	
AY | AY | AY | H164419	
BB | BB | BB | H164426	
BC | BC | BC | H164425	
NGAT | NGAT | NG.AT | L913160	
AC | AC | AC | H164410	
AA | AA | AA | H164408	
AB | AB | AB | H164409	
B1 | B1 | B1 | H160952	
B2 | B2 | B2 | H160954
B3 | B3 | B3 | H160974	
B4 | B4 | B4 | H160975	
B6 | B6 | B6 | H160976	
B7 | B7 | B7 | H160977	
B9 | B9 | B9 | H160978	
BD | BD | BD | H164427	
BE | BE | BE | H164428	
BG | BG | BG | H164429	
BH | BH | BH | H164431	
BJ | BJ | BJ | H164430
BK | BK | BK | H164445	
BL | BL | BL | H164432	
BN | BN | BN | H164446	
BP | BP | BP | H164443	
BR | BR | BR | H164447	
BS | BS | BS | H164449	
BT | BT | BT | H164448	
BX | BX | BX | H164450	
C4 | C4 | C4 | H160982	
C6 | C6 | C6 | H160983
C7 | C7 | C7 | H160984	
C9 | C9 | C9 | H160985	
CC | CC | CC | H160989	
CD | CD | CD | H160986	
CE | CE | CE | H160987	
CG | CG | CG | H160988	
CH | CH | CH | H160990	
CJ | CJ | CJ | H160991	
CK | CK | CK | H160992	
CL | CL | CL | H160993
CN | CN | CN | H160994	
CP | CP | CP | H161000	
CR | CR | CR | H167402	
CS | CS | CS | H167403	
CT | CT | CT | H167405	
CX | CX | CX | H167406	
CY | CY | CY | H167407	
D2 | D2 | D2 | H167427	
D3 | D3 | D3 | H167428	
D4 | D4 | D4 | H167429
D6 | D6 | D6 | H167430	
D7 | D7 | D7 | H167431	
D9 | D9 | D9 | H167432	
DD | DD | DD | H167433	
DE | DE | DE | H167434	
DG | DG | DG | H167435	
DH | DH | DH | H167436	
DJ | DJ | DJ | H167437	
DK | DK | DK | H167438	
FAAV | FAAV | FAA.V | H145684

**Comment by EricStienen** [comment]
All three gull rings were amended (KPAJ, NGAT & FAAV). Other codes concern differnt species and are the responsibility of Geert, Filiep etc. But I am sure that in these cases the date of applying the metal ring = date of applying colour ring. Can you change that automatically or should I do it one by one in the database (quite some work)?

**Comment by damianooldoni** [comment]
@EricStienen Thanks. I can do it while mapping the data in R. No need to add anything at db level.
