### ISSUE TITLE
metal rings not present while action rngme present in observations

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#35]
I found 30 birds with an associated `rngme` action but no metal ring information in field `MetaalringNummer` of `tblKleurring`. Here below the bird `Nummer`, the date of action `rngme` and the observation id:

bird color ring (`Nummer` from tblKleurring) | observation id (`Nummer` from tblWaarneming) | date of `rngme`
--- | --- | ---
AABA | 34128 | 2007-07-13		
AABB | 122255 | 2016-06-27		
AABC | 122530 | 2014-07-18		
AABD | 122532 | 2008-07-09		
AABE | 122534 | 2006-07-03		
AABF | 122536 | 2006-07-03		
AABG | 122538 | 2006-07-10		
AABH | 122576 | 2006-07-10		
AABI | 122577 | 2008-07-15	
AABK | 122849 | 2008-07-11
AABL | 122850 | 2008-07-15		
AABM | 122851 | 2008-07-15		
AABN | 122852 | 2008-07-07		
AABO | 122853 | 2008-07-15		
AABP | 122854 | 2008-07-02		
AABR | 122856 | 2008-07-18		
AABS | 122857 | 2009-06-29		
AABT | 122858 | 2010-06-30		
AABW | 122861 | 2010-07-05		
AABX | 122862 | 2010-06-30	
AABY | 122863 | 2010-06-30		
AABZ | 122864 | 2010-07-09		
BABA | 122906 | 2011-06-27		
BABB | 122907 | 2011-07-12		
BABD | 122909 | 2012-07-06		
BABE | 122910 | 2008-07-09		
BABF | 122911 | 2011-06-27		
BABG | 122425 | 2011-06-27		
RPAH | 109672 | 2015-07-08		
RZAV | 109701 | 2015-07-08	

Some ideas about it? Thanks a lot.

**Comment by EricStienen** [comment]
AABA to BABG are in fact non-existing codes used used to enter chicks that where initially ringed (but rings were re-used for other individuals) but that did not survive the chick-period. They never received a metal ring. RPAH and RZAV do have metal rings but the ringnumber was lost (not written down in notebook). 

I suggest to leave it as it is and keep the metalringnr blanc for all these birds!

**Comment by damianooldoni** [comment]
Thanks @EricStienen , I will do.
