### ISSUE TITLE
Solve ambiguity metal rings linked to MKAU and GPS28

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#36]
In https://github.com/inbo/sovon/issues/30 we decided the right sequence of MKAU - CZOZ (aka GPS28). That was nice.
However, I have problems while trying to link this rings to a metal ring number. I read these two rows in tblKleurring table of db:

Nummer | NummerNieuw | NummerDesc | EuringCode | GeslachtCode | MetaalringNummer
--- | --- | --- | --- | --- | --- 
MKAU | MKAU | MK.AU | 05920 | O | H152676	
GPS28 | CZOZ | C.ZOZ | 5920 | V | H903604

I can handle this double entry but I should know which metal ring number is the correct one as it is the only case of multiple metal ring in all database. I also checked in tables obs/actions: this is the only bird which is linked to two `rngme` actions. 
Same ambiguity for sex: it has been ringed while being an adult, I see, so I assume that sex should be `V`. About EuringCode , the right one is 05920.
@EricStienen : do you know which metal ring should I use? I can solve this while mapping. If you want, you don't have to modify anything at db level. As you wish.

**Comment by damianooldoni** [comment]
@EricStienen: about actions, as I wrote, this is the only bird linked to two `rngme`

Nummer(Waarneming) | KleurringNummer | Datum | AktieCode | Nummer (Aktie)
--- | --- | --- | --- | ---
57897 | GPS28 | 2010-07-30 | rngme | 68694
133648 | MKAU | 2018-09-28 | rngme | 149602

and two `rngkl`

Nummer (Waarneming) | KleurringNummer | Datum | AktieCode | Nummer (Aktie)
--- | --- | --- | --- | ---
57897 | GPS28 | 2010-07-30 | rngme | 68693
133648 | MKAU | 2018-09-28 | rngme | 149601

As I have already the mapping of all GP** and GPS** birds (see file [map_gps_id_to_color_ring.tsv]( https://github.com/inbo/sovon/blob/master/data/input/map_gps_id_to_color_ring.tsv)), the most recent actions are not only not needed, but introduce uniqueness issues. I can solve it ad hoc (already done for `rngkl` and for rings) but they could be removed at db level as well. Thanks.

**Comment by EricStienen** [comment]
solved at database level

**Comment by damianooldoni** [comment]
Thank you a lot, @EricStienen . Issue can be closed.

**Comment by EricStienen** [comment]
solved at DB level
