### ISSUE TITLE
Different ages for same date

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#37]
While working on the mapping of field `bird_age_ringing`, I found that the following birds got different age codes at the same date, which is obviously not possible. Here below the needed information from tables `tblWaarneming` en `tblWaarnemingAktie`, saved also as a file: [./data/interim/inconsistencies_bird_age_ringing.tsv](https://raw.githubusercontent.com/inbo/sovon/master/data/interim/inconsistencies_bird_age_ringing.tsv)

Nummer | KleurringNummer | Datum | LeeftijdCode | AktieCode
--- | --- | --- | --- | ---
3402 | ACAJ | 2001-08-10T00:00:00Z | J1 | veld
4381 | ACAJ | 2001-08-10T00:00:00Z | I3 | veld
2146 | AKAK | 2000-09-18T00:00:00Z | J1 | veld
2280 | AKAK | 2000-09-18T00:00:00Z | I2 | veld
2281 | AKAK | 2000-09-18T00:00:00Z | I2 | veld
119608 | AROW | 2016-07-15T00:00:00Z | PU | rngkl
119608 | AROW | 2016-07-15T00:00:00Z | PU | rngme
119609 | AROW | 2016-07-15T00:00:00Z | J1 | veld
5912 | ATAW | 2002-04-26T00:00:00Z | AD | veld
7029 | ATAW | 2002-04-26T00:00:00Z | I4 | veld
607 | BHAC | 1999-07-09T00:00:00Z | PU | rngkl
607 | BHAC | 1999-07-09T00:00:00Z | PU | rngme
806 | BHAC | 1999-07-09T00:00:00Z | J1 | veld
5955 | BMAZ | 2002-05-13T00:00:00Z | AD | veld
7493 | BMAZ | 2002-05-13T00:00:00Z | I4 | veld
2318 | BWAM | 2000-08-17T00:00:00Z | AD | veld
3837 | BWAM | 2000-08-17T00:00:00Z | J1 | veld
10830 | BWAU | 2002-10-21T00:00:00Z | AD | veld
14434 | BWAU | 2002-10-21T00:00:00Z | I3 | veld
10826 | BXAH | 2002-10-21T00:00:00Z | AD | veld
14435 | BXAH | 2002-10-21T00:00:00Z | I3 | veld
8398 | BXAH | 2002-10-21T00:00:00Z | AD | veld
10825 | BYAA | 2001-10-16T00:00:00Z | AD | veld
14436 | BYAA | 2001-10-16T00:00:00Z | I2 | veld
10822 | BYAB | 2001-10-16T00:00:00Z | AD | veld
14437 | BYAB | 2001-10-16T00:00:00Z | I3 | veld
3381 | BZAA | 2001-11-19T00:00:00Z | I3 | veld
3411 | BZAA | 2001-11-19T00:00:00Z | I2 | veld
8354 | BZAA | 2002-10-30T00:00:00Z | I3 | veld
9003 | BZAA | 2002-10-30T00:00:00Z | I2 | veld
8352 | BZAH | 2002-10-29T00:00:00Z | I3 | veld
8449 | BZAH | 2002-10-29T00:00:00Z | I3 | veld
9000 | BZAH | 2002-10-29T00:00:00Z | I4 | veld
66498 | CFAR | 2011-05-15T00:00:00Z | I3 | veld
66977 | CFAR | 2011-05-15T00:00:00Z | I4 | veld
72159 | CLAR | 2011-10-28T00:00:00Z | AD | veld
72165 | CLAR | 2011-10-28T00:00:00Z | I3 | veld
133340 | CWOB | 2018-09-15T00:00:00Z | I4 | veld
133501 | CWOB | 2018-09-15T00:00:00Z | I2 | veld
42524 | FCAV | 2008-11-15T00:00:00Z | AD | veld
42557 | FCAV | 2008-11-15T00:00:00Z | AD | veld
42889 | FCAV | 2008-11-15T00:00:00Z | I2 | veld
56346 | FSAP | 2010-02-08T00:00:00Z | AD | veld
56352 | FSAP | 2010-02-08T00:00:00Z | I4 | veld
37923 | FTAD | 2008-08-20T00:00:00Z | I3 | veld
33338 | FTAD | 2008-08-20T00:00:00Z | AD | veld
135298 | FUOV | 2018-11-05T00:00:00Z | J1 | veld
135351 | FUOV | 2018-11-05T00:00:00Z | AD | veld
44390 | FVAT | 2008-09-19T00:00:00Z | I3 | veld
34590 | FVAT | 2008-09-19T00:00:00Z | I2 | veld
24190 | FXAN | 2007-09-03T00:00:00Z | I2 | veld
25162 | FXAN | 2007-09-03T00:00:00Z | I3 | veld
33848 | GCAB | 2008-02-07T00:00:00Z | AD | veld
33849 | GCAB | 2008-02-07T00:00:00Z | I3 | veld
30023 | GFAF | 2007-11-04T00:00:00Z | AD | veld
30662 | GFAF | 2007-11-04T00:00:00Z | J1 | veld
66708 | HCAG | 2011-05-13T00:00:00Z | AD | veld
75282 | HCAG | 2011-05-13T00:00:00Z | I4 | veld
49547 | HSAR | 2009-09-20T00:00:00Z | I2 | veld
56135 | HSAR | 2009-09-20T00:00:00Z | I3 | veld
47116 | LUAL | 2009-10-01T00:00:00Z | J1 | veld
49390 | LUAL | 2009-10-01T00:00:00Z | I2 | veld
92861 | MJAD | 2013-08-07T00:00:00Z | PU | rngkl
92861 | MJAD | 2013-08-07T00:00:00Z | PU | rngme
93165 | MJAD | 2013-08-07T00:00:00Z | J1 | veld
92268 | NKAZ | 2013-06-22T00:00:00Z | AD | veld
92313 | NKAZ | 2013-06-22T00:00:00Z | I4 | veld
79890 | SGAM | 2012-08-30T00:00:00Z | I2 | veld
79939 | SGAM | 2012-08-30T00:00:00Z | J1 | veld
92862 | THAM | 2013-08-07T00:00:00Z | PU | rngkl
92862 | THAM | 2013-08-07T00:00:00Z | PU | rngme
96343 | THAM | 2013-08-07T00:00:00Z | J1 | veld
92810 | THAS | 2013-08-07T00:00:00Z | PU | rngkl
92810 | THAS | 2013-08-07T00:00:00Z | PU | rngme
93155 | THAS | 2013-08-07T00:00:00Z | J1 | veld
92828 | THAW | 2013-08-07T00:00:00Z | PU | rngkl
92828 | THAW | 2013-08-07T00:00:00Z | PU | rngme
93166 | THAW | 2013-08-07T00:00:00Z | J1 | veld
92808 | TJAD | 2013-08-07T00:00:00Z | PU | rngkl
92808 | TJAD | 2013-08-07T00:00:00Z | PU | rngme
93153 | TJAD | 2013-08-07T00:00:00Z | J1 | veld
92857 | TJAG | 2013-08-07T00:00:00Z | PU | rngkl
92857 | TJAG | 2013-08-07T00:00:00Z | PU | rngme
93163 | TJAG | 2013-08-07T00:00:00Z | J1 | veld
92812 | TJAT | 2013-08-07T00:00:00Z | PU | rngkl
92812 | TJAT | 2013-08-07T00:00:00Z | PU | rngme
93157 | TJAT | 2013-08-07T00:00:00Z | J1 | veld
92818 | TKAG | 2013-08-07T00:00:00Z | PU | rngkl
92818 | TKAG | 2013-08-07T00:00:00Z | PU | rngme
93161 | TKAG | 2013-08-07T00:00:00Z | J1 | veld
92819 | TLAA | 2013-08-07T00:00:00Z | PU | rngkl
92819 | TLAA | 2013-08-07T00:00:00Z | PU | rngme
93162 | TLAA | 2013-08-07T00:00:00Z | J1 | veld
92853 | TLAD | 2013-08-07T00:00:00Z | PU | rngkl
92853 | TLAD | 2013-08-07T00:00:00Z | PU | rngme
93160 | TLAD | 2013-08-07T00:00:00Z | J1 | veld
92822 | TLAN | 2013-08-07T00:00:00Z | PU | rngkl
92822 | TLAN | 2013-08-07T00:00:00Z | PU | rngme
93164 | TLAN | 2013-08-07T00:00:00Z | J1 | veld
92846 | TPAR | 2013-08-07T00:00:00Z | PU | rngkl
92846 | TPAR | 2013-08-07T00:00:00Z | PU | rngme
93151 | TPAR | 2013-08-07T00:00:00Z | J1 | veld
92265 | TZAH | 2013-06-22T00:00:00Z | I2 | veld
92316 | TZAH | 2013-06-22T00:00:00Z | I3 | veld
92811 | UFAF | 2013-08-07T00:00:00Z | PU | rngkl
92811 | UFAF | 2013-08-07T00:00:00Z | PU | rngme
93156 | UFAF | 2013-08-07T00:00:00Z | J1 | veld
92848 | YJAK | 2013-08-07T00:00:00Z | PU | rngkl
92848 | YJAK | 2013-08-07T00:00:00Z | PU | rngme
93158 | YJAK | 2013-08-07T00:00:00Z | J1 | veld
92847 | YJAW | 2013-08-07T00:00:00Z | PU | rngkl
92847 | YJAW | 2013-08-07T00:00:00Z | PU | rngme
93152 | YJAW | 2013-08-07T00:00:00Z | J1 | veld

@EricStienen: could you please check it and let me know which age code should I take? I see two ways to do it:

1. Solve inconsistencies at db level
2. Edit the [file](https://raw.githubusercontent.com/inbo/sovon/master/data/interim/inconsistencies_bird_age_ringing.tsv) by adding a column containing **only** the right age code, no spaces or punctuation marks. Small example:

Nummer | KleurringNummer | Datum | LeeftijdCode | AktieCode | LeeftijdCode_opgelost | Notes
--- | --- | --- | --- | --- | --- | ---
3402 | ACAJ | 2001-08-10T00:00:00Z | J1 | veld | J1 | facultative column
4381 | ACAJ | 2001-08-10T00:00:00Z | I3 | veld | J1 | if you want
2146 | AKAK | 2000-09-18T00:00:00Z | J1 | veld | I2 | to add
2280 | AKAK | 2000-09-18T00:00:00Z | I2 | veld | I2 | a comment
2281 | AKAK | 2000-09-18T00:00:00Z | I2 | veld | I2 | ...

If the problem is not the age but the date, the same two options are valid. For option 2 add column `Datum_opgelost`. 
Thank you very much for checking it!

**Comment by EricStienen** [comment]
Hi Damiano,

The field age shows the age of the bird as it was reported by the observer. However in gulls it is sometimes extremely difficult to jusdge the true age. So it is very well possible that different ages are reported at the same date. No problem! The only valid record of age is the age at ringing (rngkl).

**Comment by damianooldoni** [comment]
Thanks @EricStienen ! Indeed, if I limit my check on observations with action `rngkl` and `rngme` no problems found. :+1: 
Issue solved.
