### ISSUE TITLE
Bird sex assessment

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#38]
While checking consistency of bird sex (column `GeslachtCode` of table `tblKleurring`) I see that the information about sex of following birds is missing:

NummerNieuw | NummerDesc | Nummer | GeslachtCode
--- | --- | --- | ---
UNAW | UNAW | U.NAW | 
BABV | BABV | BABV | 

@EricStienen : should it be `O` (_onbekend_)? Could you please check it and let me know?

**Comment by EricStienen** [comment]
solved at DB level

**Comment by damianooldoni** [comment]
Wow, that's fast! 
:bullettrain_side::dash: 
Thanks. Issue can be closed.

**Comment by damianooldoni** [comment]
I reopen this issue as I found a bird with missing value in column `geslachtCode`. Color ring: LHOW.
@EricStienen : could you please check this? Thanks.

**Comment by EricStienen** [comment]
solved at DB-level

**Comment by damianooldoni** [comment]
Confirmed. Issue can be closed again
