### ISSUE TITLE
Bird age at the moment of observation not in SOVON mapping

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#40]
In SOVON expected observation table (crbirding_observations sheet of file [uitleg_invoer_data_crbirding_submit.xlsx](https://github.com/inbo/sovon/blob/master/data/input/Uitleg%20invoer%20data%20crbirding%20submit.xlsx)) I don't find any field containing the age of the bird at the moment of the observation.
The only age related field is `bird_age_ringing`, the age of the bird while applying the color ring.

SOVON: am I wrong? Is there a field where saving the estimated age as provided by observers? I know, the age while ringing is way more important.

@EricStienen: in INBO database the age as reported by observer is in field `LeeftijdCode` of `tblWaarneming`. Is it a field which we really want to have? I don't think it is such important as age is difficult to estimate (see your comment https://github.com/inbo/sovon/issues/37#issuecomment-454741499).

**Comment by damianooldoni** [comment]
Lisenka's answer: 
> We hebben op het tabblad `crbirding_observations` inderdaad alleen de leeftijd op het moment van ringen nodig. Zoals Eric Stienen al aangeeft is het moeilijk om de leeftijd te schatten wanneer een vogel in het veld wordt geobserveerd. Deze is beter te bepalen wanneer de vogel wordt geringd.
U kunt hier dus dezelfde waardes gebruiken als dat er op het tabblad `crbirding_birds` is ingevuld.

@EricStienen : so, now the ball is in your court. The estimated age of the bird as given by observer will be lost. Do you want to save it as an annotation in `observation_notes`?

**Comment by EricStienen** [comment]
We always check the age at the moment of observation in order to find reading mistakes of the code (which quite often happens). Often  this helps us to identify the true code. In other words the age when the bird was observed (although not always 100% precise) provides an additional check. I would truly encourage that this field could be included in the obeservation form. Not in the notes, but as a separete age-field!

**Comment by damianooldoni** [comment]
We see that it has been added. So, it is possible to add this directly to the SOVON database. I will ask to Lisenka which name should we give to this new field.

**Comment by damianooldoni** [comment]
Lisenka's answer:

> Een kleine correctie op wat ik de vorige keer heb gezegd. We gebruiken inderdaad alleen de leeftijd op het moment van ringen, die is ingevuld bij crbirding_birds in de kolom bird_age_ringing, om leeftijd te berekenen.
> Op het tabblad crbirding_observations is als het goed is ook een kolom aangewezig die bird_age_ringing heet. Deze wordt niet gebruikt voor het bepalen van de leeftijd. Nu de correctie: in de kolom bird_age_ringing op het tabblad crbirding_observations kun je de leeftijd op het moment van de observatie invullen, zoals hij door de waarnemer is doorgegeven (en dus niet de ringleeftijd).
> Excuses voor de verwarring.

**Comment by damianooldoni** [comment]
@EricStienen : I think this will make you happy, isn't?

**Comment by EricStienen** [comment]
yes!

**Comment by damianooldoni** [comment]
I was wondering about the name of this field after the meaning shift, why don't use `bird_age` instead of `bird_age_ringing`?

Lisenka's answer:
> De naam klopt inderdaad niet echt, dus ik heb hem aan mijn kant al veranderd. Ik ben gegaan voor `bird_age_obs`, maar ik vind bird_age ook prima.

So, I changed to `bird_age_obs` as I find it even better than my first idea.
