### ISSUE TITLE
How to select observations with metal ring not present

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#41]
While mapping the field Metal Ring Information (MRI, see table at page 8 of [EURING Exchange Code 2000+](https://euring.org/files/documents/E2000PLUSExchangeCodev1161.pdf)), I try to select the observations where metal ring is not present (code 0). I thought to use the date in `Datum` linked to actions `meweg` (metal ring missing) as the very first observation when metal ring is not present. We are speaking about thee observations of 107 birds.

However, it happens that 34 of them are also linked to one or more following `vang` (caught at the nest).  Here below some overview, that you can also get as a file [/data/interim/meweg_followed_by_vang.tsv](https://raw.githubusercontent.com/inbo/sovon/master/data/interim/meweg_followed_by_vang.tsv):

Nummer | EuringCode | KleurringNummer | Datum | AktieCode
--- | --- | --- | --- | ---
17753 | 05910 | ACAJ | 2006-04-21 | meweg
16459 | 05910 | ACAJ | 2006-05-23 | vang
57943 |  | AFAB | 2009-04-01 | meweg
45389 | 05910 | AFAB | 2009-05-29 | vang
17932 | 05910 | AHAS | 2006-04-21 | meweg
45725 | 05910 | AHAS | 2009-06-05 | vang
24786 | 05910 | AJAA | 2007-05-17 | meweg
45636 | 05910 | AJAA | 2009-05-22 | vang
17956 | 05910 | AJAD | 2006-03-31 | meweg
28734 | 05910 | AJAD | 2007-06-11 | vang
17971 | 05910 | AJAK | 2006-04-21 | meweg
16641 | 05910 | AJAK | 2006-05-24 | vang
80181 |  | AJAT | 2012-05-01 | meweg
79004 | 05920 | AJAT | 2012-05-16 | vang
67238 | 05910 | AKAU | 2011-05-24 | meweg
67238 | 05910 | AKAU | 2011-05-24 | vang
24884 | 05910 | AMAL | 2007-04-06 | meweg
45610 | 05910 | AMAL | 2009-05-29 | vang
24930 | 05910 | ANAN | 2007-03-09 | meweg
45478 | 05910 | ANAN | 2009-05-14 | vang
24982 | 05910 | ASAP | 2007-05-02 | meweg
80193 |  | ASAP | 2012-06-14 | vang
15172 | 05910 | ASAX | 2005-06-14 | meweg
33471 | 05910 | ASAX | 2008-05-21 | vang
13817 | 05910 | ASAY | 2005-06-17 | meweg
45515 | 05910 | ASAY | 2009-05-18 | vang
34945 | 05910 | AUAP | 2008-04-04 | meweg
33563 | 05910 | AUAP | 2008-06-04 | vang
25029 | 05910 | AVAD | 2007-03-28 | meweg
79024 | 05910 | AVAD | 2012-05-22 | vang
35047 | 05910 | BBAX | 2008-03-12 | meweg
45651 | 05910 | BBAX | 2009-05-22 | vang
15491 | 05910 | BCAV | 2005-04-08 | meweg
45739 | 05910 | BCAV | 2009-06-01 | vang
35109 | 05910 | BHAW | 2008-03-12 | meweg
80220 |  | BHAW | 2012-05-29 | vang
57935 |  | BJAA | 2009-03-24 | meweg
45496 | 05910 | BJAA | 2009-05-14 | vang
25513 | 05910 | BJAY | 2007-05-03 | meweg
23433 | 05910 | BJAY | 2007-06-14 | vang
15724 | 05910 | BLAH | 2005-04-05 | meweg
33611 | 05910 | BLAH | 2008-05-21 | vang
25578 | 05910 | BLAR | 2007-04-18 | meweg
33571 | 05910 | BLAR | 2008-06-04 | vang
35219 | 05910 | BNAH | 2008-05-02 | meweg
55909 | 05910 | BNAH | 2008-06-06 | vang
25667 | 05910 | BSAL | 2007-03-09 | meweg
78737 | 05910 | BSAL | 2012-06-13 | vang
35258 | 05910 | BSAY | 2008-03-12 | meweg
80248 |  | BSAY | 2012-05-17 | vang
15865 | 05910 | BTAF | 2005-04-05 | meweg
67421 | 05910 | BTAF | 2011-06-03 | vang
15877 | 05910 | BTAX | 2005-04-15 | meweg
16664 | 05910 | BTAX | 2006-06-15 | vang
25763 | 05910 | BUAW | 2007-04-25 | meweg
45514 | 05910 | BUAW | 2009-05-18 | vang
35331 | 05910 | BUAZ | 2008-04-02 | meweg
32553 | 05910 | BUAZ | 2008-05-19 | vang
61955 | 05910 | BVAP | 2010-03-31 | meweg
58566 | 05910 | BVAP | 2010-05-18 | vang
25824 | 05910 | BWAK | 2007-03-07 | meweg
30053 | 05910 | BWAK | 2007-06-06 | vang
14638 | 05910 | GPS62 | 2004-11-23 | meweg
16649 | 05910 | GPS62 | 2006-05-26 | vang
103027 |  | GPS62 | 2014-06-16 | vang
35337 | 05910 | GPS98 | 2008-04-02 | meweg
109267 | 5910 | GPS98 | 2015-06-03 | vang

And a more detailed example for a single bird where I put in bold the observations linked to `meweg` and the following `vang`:

Nummer | EuringCode | KleurringNummer | Datum | AktieCode
--- | --- | --- | --- | ---
... | ... | ... | ... | ... 
35047 | 05910 | BBAX | 2008-03-12 | meweg
35048 | 05910 | BBAX | 2008-03-19 | veld
35049 | 05910 | BBAX | 2008-03-28 | veld
35050 | 05910 | BBAX | 2008-04-04 | veld
35051 | 05910 | BBAX | 2008-06-04 | br
63700 | 05910 | BBAX | 2008-10-20 | veld
47457 | 05910 | BBAX | 2009-03-27 | veld
47458 | 05910 | BBAX | 2009-04-03 | veld
47459 | 05910 | BBAX | 2009-04-09 | veld
47460 | 05910 | BBAX | 2009-04-17 | veld
47461 | 05910 | BBAX | 2009-04-23 | veld
47462 | 05910 | BBAX | 2009-05-01 | veld
47463 | 05910 | BBAX | 2009-05-06 | veld
47464 | 05910 | BBAX | 2009-05-13 | br
**45651** | **05910** | **BBAX** | **2009-05-22** | **vang**
52466 | 05910 | BBAX | 2009-06-04 | veld
52467 | 05910 | BBAX | 2009-07-01 | veld
61744 | 05910 | BBAX | 2010-02-25 | veld
56414 | 05910 | BBAX | 2010-02-27 | veld
61745 | 05910 | BBAX | 2010-03-12 | veld
61746 | 05910 | BBAX | 2010-03-18 | veld
61747 | 05910 | BBAX | 2010-03-25 | veld
61748 | 05910 | BBAX | 2010-04-07 | veld
61749 | 05910 | BBAX | 2010-04-14 | veld
64464 | 05910 | BBAX | 2010-04-29 | veld
64471 | 05910 | BBAX | 2010-05-01 | veld
64553 | 05910 | BBAX | 2010-05-15 | veld
64581 | 05910 | BBAX | 2010-05-25 | veld
59531 | 05910 | BBAX | 2010-06-03 | br
63709 | 05910 | BBAX | 2010-09-01 | veld
64216 | 05910 | BBAX | 2010-10-13 | veld
68472 | 05910 | BBAX | 2011-03-25 | veld
68471 | 05910 | BBAX | 2011-04-01 | veld
68470 | 05910 | BBAX | 2011-04-08 | veld
68469 | 05910 | BBAX | 2011-04-26 | veld
68468 | 05910 | BBAX | 2011-05-12 | veld
68465 | 05910 | BBAX | 2011-05-26 | br
68466 | 05910 | BBAX | 2011-06-24 | veld
68467 | 05910 | BBAX | 2011-07-06 | veld

@EricStienen : get the bird a new metal ring at the moment of `vang`? Always? And if yes, where can I know the new ring? This issue is partly related to #34. I hope you have a (easy) solution :smiley:  Thanks.

**Comment by EricStienen** [comment]
Yes they receive a new metal ring at "vang". The metal ring mentioned in our database is always the most recent ring. The old metalring is normally mentioned in the field "omschrijving". However, our database (as well as the SOVON-database) is conceived around colour rings and information about the metalring is not very important.  I should not bother about the various metal ring codes that a bird had during its life. Only the latest metal ring nr is relevant.

**Comment by damianooldoni** [comment]
Thanks @EricStienen : then, if you are not bothered about it, I will leave the field MRI of `crbirding_observations` empty. The metal ring number is still saved in the table `crbirding_birds`, exactly as you did at INBO.  Ok?

**Comment by EricStienen** [comment]
yes fine for me!
