### ISSUE TITLE
SOVON field `Ringnumber` vs SOVON field `Ringnumber` in obs table

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#42]
I am wondering about the SOVON field `Ringnumber` in table `crbirding_observations`, which should be filled with the metal ring number. In our database this field is almost never filled:

MetaalringNummer | number of obs/actions
--- | ---
NA | 133959
not NA | 1171

Moreover, as discussed in #24 it is not always correct (the right metal ring number is in table `kleurring`). 
I would opt for leaving this field empty as we decided to do for field MRI (see #41).
@EricStienen: what do you think?

**Comment by EricStienen** [comment]
In fact all the details that are given in our databasetable "kleurring" (species, metalring number, old colour ring, sex) are the correct values! Whenever one of these values are filled in in the table "waarneming" they can be discarded (or in the case of species treated as "species as assumed by the observer").  A special case is the age of the bird. Age is only mentioned in the table "waarneming". As explained in earlier conversations only the age at the moment of applying the colour ring is the correct age. In all other cases where age is filled in in the table "waarneming" it is the "age as assumed by the observer".

**Comment by damianooldoni** [comment]
Yes, thanks for reminder! :+1: 
So, the values `MetaalringNummer` in `tblWaarneming` are the values "as assumed by the observer"?

**Comment by EricStienen** [comment]
I have no idea how these values appeared in the tblWaarneming. In principle it is not possible to enter these values in that table. They can all be deleted!

**Comment by damianooldoni** [comment]
Thanks. I close this issue then. 
I opened a new one (#44) about the general mapping of SOVON field `Ringnumber` in table `crbirding_observations`, which will be based on Lisenka's answer on #43. Still, I think (hope) that leaving it empty would be not a big deal for SOVON.
