### ISSUE TITLE
Can bird be assumed dead for klgev

### ISSUE THREAD

**Issue by peterdesmet** [inbo/sovon#49]

**Comment by damianooldoni** [comment]
@EricStienen : yesterday @peterdesmet and I were wondering about action `klgev`.
Can we assume that the bird is dead? 
Possible combinations of actions found:

1. `klgev` only: 36 observations. Observation with `Nummer`:
122531 127889 120916 127499   2014  12080 127952 116584  61151 122914 122426 128295   8268 127539 128118 127953 114174  32138  69276  32373 129637  92262  61545 127260 126625 121430 127631  93230  78951  99050  99047  92530  99048 111616 116586 109382

2. `klgev` - `rngkl`: 1 observation. Observation with `Nummer`:
67962

Could be that the latter one means that the ringer found a color ring (of a dead bird?) and at the same time applied a ring to another one (in field `Opmerking`: _"Pullus 2 van 4"_)?

**Comment by EricStienen** [comment]
The last issue (nr 67962) was an error and is adjusted in the database.

In all the other cases only the colour ring was found and this often means that the bird dided, but we also have cases of birds where we know for sure that the colour ring is lost. 

So the answer to your question is: NO we can not assume that the bird is dead.

**Comment by damianooldoni** [comment]
Thanks.
