### ISSUE TITLE
duplicates in tblWaarnemingAktie

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#5]
I found duplicates in table `tblWaarnemingAktie`, that means two different lines referring to same observation (`WaarnemingNummer`) with same action code (`AktieCode`)  and datums (`AanmaakDatum`, `WijzigDatum`):

WaarnemingNummer | Nummer | AktieCode | AanmaakDatum | WijzigDatum
--- | --- | --- | --- | --- | 
108630 | 122234 | veld | 2015-09-03 14:25:00 | 2015-09-03 14:26:00
108630 | 122235 | veld | 2015-09-03 14:25:00 | 2015-09-03 14:26:00
108631 | 122236 | veld | 2015-09-03 14:26:00 | 2015-09-03 14:26:00
108631 | 122237 | veld | 2015-09-03 14:26:00 | 2015-09-03 14:26:00
125101 | 140474 | rngkl | 2017-10-03 09:15:00 | 2017-10-03 09:15:00
125101 | 140475 | rngkl | 2017-10-03 09:15:00 | 2017-10-03 09:15:00
125102 | 140476 | rngkl | 2017-10-03 09:15:00 | 2017-10-03 09:15:00
125102 | 140477 | rngkl | 2017-10-03 09:15:00 | 2017-10-03 09:15:00
125103 | 140478 | rngkl | 2017-10-03 09:16:00 | 2017-10-03 09:16:00
125103 | 140479 | rngkl | 2017-10-03 09:16:00 | 2017-10-03 09:16:00

How should I interpret these data? Should I just apply R function `distinct()` in order to remove such duplicates?

There are also other two `WaarnemingNummer` values with two duplicates each with different `AanmaakDatum`/`WijzigDatum`:

WaarnemingNummer | Nummer | AktieCode | AanmaakDatum | WijzigDatum
--- | --- | --- | --- | --- | 
109768 | 123607 | veld | 2015-10-21 14:03:00 | 2015-10-21 14:11:00
109768 | 135067 | veld | 2017-05-17 21:22:00 | 2017-05-17 21:22:00
131531 | 147273 | rngkl | 2018-08-17 12:07:00 | 2018-09-17 17:09:00
131531 | 149239 | rngkl | 2018-09-17 17:09:00 | 2018-09-17 17:09:00

Same problem: how should I interpret these duplicates? Should I remove the duplicates? But in this case what should I retain and what discard?

**Comment by damianooldoni** [comment]
Answer of Eric: 
> Die dubbels worden vandaag nog met de hand verwijderd door Marc. Vanavond kun je de analyse nogmaals uitvoeren op het geupdatede bestand en dan zouden er geen dubbels meer in moeten zitten.

Duplicates are errors and will be removed.

**Comment by damianooldoni** [comment]
Previous duplicates have been removed as mentioned by [Eric](https://github.com/inbo/sovon/issues/5#issuecomment-423946410). Thanks. 
However, new duplicates seem appear:

WaarnemingNummer | Nummer | AktieCode | AanmaakDatum | WijzigDatum
--- | --- | --- | --- | --- 
125104 | 140480 | rngkl | 2017-10-03 09:16:00 | 2017-10-03 09:16:00
125104 | 140481 | rngkl | 2017-10-03 09:16:00 | 2017-10-03 09:16:00
125105 | 140482 | rngkl | 2017-10-03 09:16:00 | 2017-10-03 09:16:00
125105 | 140483 | rngkl | 2017-10-03 09:16:00 | 2017-10-03 09:16:00
125106 | 140484 | rngkl | 2017-10-03 09:16:00 | 2017-10-03 09:16:00
125106 | 140485 | rngkl | 2017-10-03 09:16:00 | 2017-10-03 09:16:00
125107 | 140486 | rngkl | 2017-10-03 09:17:00 | 2017-10-03 09:17:00
125107 | 140487 | rngkl | 2017-10-03 09:17:00 | 2017-10-03 09:17:00

Could you please have a look? I can remove them without problems while mapping to SOVON, but for integrity it is good practice to remove them from database as well.

**Comment by damianooldoni** [comment]
Duplicates have been deleted at db level. Thanks. 
However, I will not remove the check in pipeline:
```r
obs_actions %>% filter(raw_WaarnemingNummer %in% 
                         (obs_actions %>% 
                         group_by(raw_WaarnemingNummer, 
                                  raw_AktieCode) %>% 
                         count() %>%
                         filter(n > 1) %>%
                         pull(raw_WaarnemingNummer)))
```

and the code removing such duplicates:

```r
obs_actions <- obs_actions %>% 
  distinct(raw_WaarnemingNummer, 
           raw_AktieCode, .keep_all = TRUE)
```

**Comment by damianooldoni** [comment]
I found duplicates for ringing action (rngkl). Here below details from table `tblWaarneming`:

Nummer | Datum | EuringCode | KleurringNummer
--- | --- | --- | ---
151942 | 2020-06-29 00:00:00 | 5910 | KAOL
152358 | 2020-06-29 00:00:00 | 5910 | KAOL
152373 | 2020-06-29 00:00:00 | 5910 | KDOU
152372 | 2020-06-29 00:00:00 | 5910 | KDOU
152131 | 2020-07-17 00:00:00 | 5910 | KTOH
152538 | 2020-07-17 00:00:00 | 5910 | KTOH
152421 | 2020-07-13 00:00:00 | 5920 | LJOK
152420 | 2020-07-13 00:00:00 | 5920 | LJOK
152178 | 2020-07-13 00:00:00 | 5920 | LNOV
152177 | 2020-07-13 00:00:00 | 5920 | LNOV

@EricStienen : could you please give a look to this? Thanks!

**Comment by damianooldoni** [comment]
I found also duplicates for the very same five birds for metal ringing action, `rngme`.

**Comment by EricStienen** [comment]
both issues (double cr and double metal) are solved

**Comment by damianooldoni** [comment]
Confirmed. Thanks @EricStienen. Issue can be closed again.
