### ISSUE TITLE
Split script

### ISSUE THREAD

**Issue by peterdesmet** [inbo/sovon#51]
Please split script into:

## 1_preprocessing.Rmd

Script until:

https://github.com/inbo/sovon/blob/3e1e6636195a3a2d0fe94828becc19d60ce98d05/src/map_inbo_data_to_sovon.Rmd#L592

Should result in:

```
data/interim/users.tsv (gitignore!)
data/interim/obs_and_actions.tsv
data/interim/birds.tsv
```

## 2_users.Rmd

Starts from interim file, writes to:

```
data/processed/crbirding_users.tsv (gitignore!)
```

## 3_birds.Rmd

Starts from interim file, writes to:

```
data/processed/crbirding_birds.tsv
```

## 4_observations.Rmd

Starts from interim file, writes to:

```
data/processed/crbirding_observations.tsv
```

**Comment by damianooldoni** [comment]
Done
