### ISSUE TITLE
duplicates in tblWaarneming

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#52]
@EricStienen: could you please check the observations with number 66839 and 66840, please? They seem to be a duplicate, isn't? Same action too.

**Comment by EricStienen** [comment]
Could you please specify the colour ring code and dates? I have no access to the observation numbers.

**Comment by damianooldoni** [comment]
`Datum`: 2008-02-10
`KleurringNummer`: A3
`EurringCode`: 01730
`LeeftijdCode`: AD
`PlaatsGemeente`: Destelbergen
`WaarnemerNummer`: 392

The two observations are both linked to `AktieCode`: vang

**Comment by EricStienen** [comment]
solved at DB level.

I just heard last week that the of Common Shelduck is not up to date at all and that there is more data sitting in a personal database of Nico de Regge. Probably better to not include this species in this session, but add the data in a later stage.

**Comment by damianooldoni** [comment]
Thanks. about, data of Common Shelduck, I move it in a separate issue.
