### ISSUE TITLE
Changing color ring in observations with actions `br`-`klweg`

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#53]
I have just discovered that the change of a color ring is not only coupled with actions `vang` but also with some observations with actions `br` AND `klweg`. Is it possible?
See here below: the 14 observations linked to actions `br` and `klweg`:

Nummer | Datum | Opmerking
--- | --- | ---
17180 | 2006-05-23T00:00:00Z	
24743 | 2007-06-06T00:00:00Z	
24796 | 2007-06-06T00:00:00Z	
15309 | 2005-05-20T00:00:00Z	
25543 | 2007-06-07T00:00:00Z	
25691 | 2007-06-07T00:00:00Z	
109220 | 2015-05-22T00:00:00Z | "DRAW wordt verwijderd en vervangen door 6+, metaal wordt vervangen door 5508290. Krijgt bovendien GPS70 Sacha"
67847 | 2011-06-02T00:00:00Z	
136553 | 2018-05-16T00:00:00Z | blauw 83
136544 | 2017-05-23T00:00:00Z | GUAK > 54 + gps 112
109221 | 2015-05-22T00:00:00Z | "HJAB wordt verwijderd en vervangen door 7A, en krijgt GPS72 Ben | Metaalring wordt niet vervangen"
113521 | 2016-05-19T00:00:00Z | KMAW > G- 5C + gps 102
115632 | 2016-05-25T00:00:00Z | NSAN > 6M + gps-logger
136545 | 2018-07-09T00:00:00Z | TVAH > 59 + gps 113

Quite strange names for colro rings: `54`, `59`, `G-`,  `6+`

@EricStienen : How should I handle these ones? I need your advice in order to get this done asap. Thank you again.

**Comment by EricStienen** [comment]
The problem of emigrants. 

These are all cases where the bird was caught on the nest in the another country by a foreign ringer, our old colour ring was removed and a new foreign colour ring was added.  

Since we (often) do not longer receive resightings of these birds, codes are "br" and "kl-weg". Leave it as it is, I would suggest.

**Comment by damianooldoni** [comment]
Ok, I will NOT add any row in `crbirding_birds`. Thanks.
