### ISSUE TITLE
WaarnemerNummer of personnel of bird rescue teams

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#55]
Could you please send me a list of the workers in bird shelters, please?
As discussed in our meeting in Aug 2018, I need to know their observer number ID in order to assign condition equal to 5 to the observations made by them and with action code `ziek` before `dood`. 
If the list contains personal information, just reply by e-mail. 
Thanks.

**Comment by damianooldoni** [comment]
I can easily extract the following users:

1. VOC - Brasschaat
2. VOC - Merelbeke
3. VOC - Oostende

@EricStienen : are some workers registered with their own personal account?

**Comment by EricStienen** [comment]
No. We are the only users and all rings are INBO property.

**Comment by damianooldoni** [comment]
Table `tblWaarnemer` counts 1851 rows, I doubt they are all INBO employees :rofl:

**Comment by EricStienen** [comment]
No of course not, they are the observers!

**Comment by damianooldoni** [comment]
Sorry for the misunderstanding: SOVON table is called `crbirding_users`. So I used the term *users* to indicate all people in table `tblWaarnemer`.

**Comment by damianooldoni** [comment]
Users in https://github.com/inbo/cr-birding/issues/55#issuecomment-471441404 are the only one.
