### ISSUE TITLE
Condition code of observation with action code "br" only

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#56]
There are 6000+ observations linked to action code `br` (broedend) only.

Can we for sure map them to condition 7:
> Alive and probably healthy and certainly released (including ring or other mark identified on a
healthy bird without the bird having being caught).

or can we for sure map them to condition 8: 
> Alive and probably healthy and released by a ringer (including ring or other mark identified on the
bird by a ringer without the bird having being caught). 'A ringer' means any licensed ringer, not
just the ringer who ringed that bird.

In other words, are these observations performed by your team/other INBO experts (condition 8)?

I will send you immediately the list of names via e-mail for privacy reasons. As you will see 4000+ observations are performed by one person. SO, it is quite an easy question, I hope.
Thanks.

**Comment by damianooldoni** [comment]
@EricStienen :  e-mail sent

**Comment by EricStienen** [comment]
All of them should be mapped to condition 7! These birds were seen when sitting on the eggs or having chicks, but were not caught.

Condition 8 only applies for birds that were caught on the nest and in that case they received the action code "vn".

**Comment by damianooldoni** [comment]
Thank you very much!
