### ISSUE TITLE
Improve mapping MRI

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#58]
Apply color rings -> MRI 2
Apply metal rings -> MRI 1
`br` only -> MRI 4
`dood` only -> MRI 4
`br` and `dood` -> MRI 4
`meweg` -> MRI 4

**Comment by damianooldoni** [comment]
@EricStienen : which MRI should I assign to observations linked to both actions `rngkl` and `rngme`? MRI = 1 or MRI = 2?

I strongly suggest MRI = 2 as INBO and SOVON databases are "color ring minded". 
Let me know.

**Comment by EricStienen** [comment]
action code rngkl -> MRI 2 (**Colour ring** added (where no **colour ring** was present), definitely on tarsus
action code ringkl in combination with rngme = MRI 2 (**Colour ring** added (where no **colour ring** was present), definitely on tarsus
