### ISSUE TITLE
observations without related action code

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#6]
The following observations (as `Nummer`) in table `tblWaarneming` are not present in table  `tblWaarnemingAktie` (as `WaarnemingNummer`):

126208, 32607, 63740, 92592, 132866, 133161

This means there is no action code referring to them. Could you please check them? How should we evaluate them?

**Comment by damianooldoni** [comment]
Problem solved at database level by Eric and Marc.

**Comment by damianooldoni** [comment]
A very recent observation with date `2018-10-02` and number `134198` has been added without any action code related.
Moreover, all fields are empty except `Nummer`, `Datum`, `AanmaakDatum` and `WijzigDatum`.
I check for these kind of anomalies in the pre-processing and I remove them. It's up to you if you want to remove them at database level.

**Comment by damianooldoni** [comment]
Observation deleted in database. Issue solved.

**Comment by damianooldoni** [comment]
A very recent observation with date `2019-01-05` and number `137876` has been added without any action code related. @EricStienen : could you please check it? Thanks a lot!

**Comment by EricStienen** [comment]
solved ar database level

**Comment by damianooldoni** [comment]
Checked. Solved.

**Comment by damianooldoni** [comment]
I detected new three observations in table `tblWaarneming` without a related action code in table `tblWaarnemingAktie`:

Nummer | Datum | EuringCode | LeeftijdCode | KleurringNummer
--- | --- | --- | --- | ---
152243 | 2020-08-19 | 5920 | J1 | AA	
150855 | 2020-07-11 | 04560 | AD | EA07	
151931 | 2020-08-07 | 5910 |  | KLAD

@EricStienen : could you or someone of your team give a look into this? Thanks.

**Comment by EricStienen** [comment]
solved at DB level

**Comment by damianooldoni** [comment]
Yes, confirmed. Issue can be closed again.
