### ISSUE TITLE
Add information about left or right leg

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#61]
This information is asked via crbirding web application (you can put the ring on the left or right leg), so it can be easily translated to a field in `crbirding_observations`(?) Which is it?
This information is both for metal and  for color ring and it is present in INBO table `tblKleurring` as `Plaats` and `MetaalringPlaats`. Ask to SOVON:

1. Is it possible? It should be, in theory.
2. Is this information for both `crbirding_birds` and `crbirding_observations` or only `crbirding_birds` with the right value? Theoretically the the information in `crbirding_observations` could be different than the information in `crbirding_birds`, right?
2. Which name should we give to this field?
3. How are the values mapped in SOVON database? (e.g. in Dutch? In English or initials "LL"/"RL" or other?)

**Comment by damianooldoni** [comment]
Answer of Lisenka:

> Wanneer een vogel aan beide poten een gekleurde pootring heeft, wordt bij het noteren van de kleurringen altijd eerst de linkerpoot (vanuit de vogel) en vervolgens de rechterpoot (vanuit de vogel) weergegeven. Bijvoorbeeld: een vogel heeft om zijn linkerpoot een groene ring met zwarte inscriptie B02 en aan zijn rechterpoot een zware ring met witte inscriptie B03, dit wordt genoteerd als GN(B02)/NW(B03).

> Bij vogels die maar om één poot kleurringen dragen hangt het ervan af of het gaat om gekleurde ringen met inscriptie of gekleurde ringen zonder inscriptie:
> 1. Zonder inscriptie: vogel met een of meerdere gekleurde ringen (zónder inscriptie) om één poot, worden eigenlijk altijd met een metalen ring om de andere poot geringd. Bij het noteren van de code wordt daarom ook de afkorting voor de metalen ring gebruikt, waardoor kan worden aangegeven om welke poot de gekleurde ringen zitten. Bijvoorbeeld: een vogel met een gele en een oranje ring zonder inscriptie om de linkerpoot en een metalen ring om de rechterpoot (YO/M).
> 2. Met inscriptie: vogel met een gekleurde ring met inscriptie om één poot. Hierbij zijn we er tot nu toe van uit gegaan dat het niet uitmaakt om welke poot de gekleurde ring zit. We gaan er op de site eigenlijk van uit dat als er een vogel met een gekleurde ring met inscriptie om de linkerpoot is geringd, dat er dan niet nog een exemplaar van dezelfde soort met een identieke kleurring om de rechterpoot is geringd. Wanneer je op de site bij type markering voor “slechts één unieke pootring” kiest, komt er ook nog maar een pootje tevoorschijn. Mocht het echt nodig zijn om deze informatie door te geven dan kan er een extra kolom toegevoegd worden aan crbirding_birds met de naam positie_kleurring of iets dergelijks. Gebruik maar LL en RL voor linker- en rechterpoot.

**Comment by damianooldoni** [comment]
@EricStienen : see answer above. I think all our color rings are WITH inscription and we have only ONE color ring, right? As Lisenka wrote, if just one color ring exists, there is no need to save such information. But, probably you use this information for checking the validity of an observation? Let me know. If you want, I will add column `position_colorring` to `crbirding_birds` table.

**Comment by EricStienen** [comment]
Yes only one colour ring with inscription. The code is unique indeed. However, it would be very usefull that an observer can add the leg (left/right) and in which direction the ring must be read (up/down). In the past this helped us a lot when identifying mistakes in reading. 

So two columns must be added to crbirding_table (position_colorring) and (direction_colorring).

**Comment by damianooldoni** [comment]
@EricStienen : ok. I will add field `position_colorring` with possible values: `LL`, `RL` or empty if not present in `crbirding_birds` and `crbirding_observations`.

**Comment by damianooldoni** [comment]
In order to maintain the name structure of all columns of table `crbirding_birds`, I am adding position color ring and direction inscription as `bird_position` and `bird_direction` respectively. In this way all columns start with `bird_`.
