### ISSUE TITLE
Mapping of MetaalringLandCode

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#63]
INBO table `tblKleurring` contains the scheme (land code) of the metal ring. It seems from web interface (submit-cr_birding) that this information is present (e.g. NLA 1437205). Is there a field in `crbirding_birds` for it? In `crbirding_observations` too? Thanks.

**Comment by damianooldoni** [comment]
Lisenka's answer:
> Op het tabblad crbirding_birds vind je als het goed is een kolom met bird_scheme. Hier moet het ring schema ingevuld worden.

**Comment by damianooldoni** [comment]
Thanks. Actually I mapped it a lot of time ago as `bird_scheme`. 
@Lisenka: we have the following mapping

MetaalringLandCode (INBO field) | bird_scheme
--- | ---
BE | BLB
FR | FRP
NL | NLA
PT | POL
UK | GBT

@EricStienen : I don't find useful to have this field in obesrvation table as it is not maintained properly as you can see in table below.

MetaalringLandCode_obs | n
--- | ---
empty | 133457
be | 856
BE | 580
nl | 2
NL | 1

**Comment by damianooldoni** [comment]
Metal ring scheme present in `cr-birding_birds`. 
As all other fields concerning metal rings in INBO `tblKleurring`, this field is not needed as information is not complete or not correct.

**Comment by EricStienen** [comment]
indeed this field is not needed!
