### ISSUE TITLE
Observations coupled to actions veld AND klweg

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#65]
There are 5 observations linekd to actions `veld` AND `klweg`. I thought that `veld` was synonym of *color ring read*, so I find the action `klweg` coupled to `veld` quite strange. Should `veld` + `klweg` be just `me` (metal ring read)? Or am I wrong?

Here below some details:

Datum | KleurringNummer | Opmerking
--- | --- | ---
2016-11-02 00:00:00 | EK60 | blauw 7K 
2018-05-11 00:00:00 | KHAW | 6=       
2018-05-05 00:00:00 | LUAN | B-7C     
2018-05-02 00:00:00 | LZAV | 8W       
2018-05-05 00:00:00 | UJAM | 7C

**Comment by EricStienen** [comment]
That seems rather strange indeed. However, these are special cases. The Belgian colour ring was removed by a foreign ringer (in this case Dutch) who replaced by a colour ring of his own.

**Comment by damianooldoni** [comment]
@EricStienen : should I discard these observations from the mapping? Or should I leave them? The point is that if I leave them I find strange to not update also the table crbirding_birds` by adding these new rings. Let me know. Thanks.

**Comment by EricStienen** [comment]
You should leave them. They are, however, no longer our birds and the new ring should therfore not be added to the Bird table. However, the metal ring can still be read. It is compatible to a bird that lost it's colour ring. Also these birds have lost our Belgian colour ring.

**Comment by damianooldoni** [comment]
@EricStienen : thanks, I will leave them. I assign MRI value 4 (metal ring present) to these observations as any other observation with action `veld`.
