### ISSUE TITLE
MRI for combinations of actions with meweg

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#66]
@EricStienen : the mapping of action `meweg` to MRI = 4 decided yesterday was for `meweg` ONLY or any combination of actions containing `meweg`? I think the second one...

Here below all occurring combinations with action `meweg`:

br | vang | dood | klweg | veld | meweg | MRI
--- | --- | --- | --- | --- | --- | ---
 |  | | | | veld | meweg |  4
 |  | | | | | meweg |  4
 |  | vang | | | | meweg |  4
br | | | | | meweg |  4
 |  | | dood | | | meweg | 4

If this is not correct, please could you please correct it? Thanks

**Comment by EricStienen** [comment]
yes this is correct. In all cases it was observed that the metal ring was missing, which means that the colour ring was still present (=MRI 4)
