### ISSUE TITLE
Add color ring and inscription color ring to bird_shorthand

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#67]
This is how `bird_shorthand` should be mapped, based on an example sent to Lisenka and got back filled:

Lisenka:
> Deze ringen moeten op de volgende manier geschreven worden:

Inscriptie | RingKleurCode | InscriptieKleurCode| shorthand
--- | --- | --- | ---
BBAP  | B | W| BW(BBAP)
KHAA | B | Y | BY(KHAA)
NGAP | B | W| BW(NGAP)

This issue answers to issues #60 and #59.

**Comment by damianooldoni** [comment]
From @JeroenNienhuis e-mail:

> We hadden afgesproken om de vogels op te nemen als bv B-DJAU i.p.v. BW(DJAU)

Sorry, @JeroenNienhuis, I think I lost it in one of the emails.. that's why I like keeping track of things in issues :+1: 

I will do, but first I would like a final check from @jeroenNienhuis.
Using the the example above, do we agree  to change the actual `bird_shorthand` to the proposed `bird_shorthand`?

Inscriptie | RingKleurCode | InscriptieKleurCode | actual bird_shorthand | proposed bird_shorthand
--- | --- | --- | --- | ---
BBAP  | B | W| BW(BBAP) | **B-BBAP**
KHAA | B | Y | BW(KHAA) | **B-KHAA**
NGAP | B | W| BW(NGAP) | **B-NGAP**

So, if I understood correctly we remove the color of the inscription from the mapping, right?

**Comment by JeroenNienhuis** [comment]
Correct

**Comment by damianooldoni** [comment]
This was indeed discussed here: https://github.com/inbo/cr-birding/issues/107#issuecomment-498343225
