### ISSUE TITLE
Data transfer to SOVON database

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#68]
E-mail to SOVON:

De einde van de mapping lijkt niet meer ver te zijn, gelukkig. Het is dus tijd om een datum te bepalen voor de gegevensoverdracht.

Kunnen de INBO gegevens effectief in de databank geschreven worden tussen 8 en 12 april? Om deze datum praktisch te halen, past het bij jullie als ik ten laatste op 1 april de drie tabellen, crbirding_users/birds/observations zal sturen? We hebben dan minimum een week voor review. Ik schat het genoeg aangezien dat de mapping grondig gediscussieerd is geweest via GitHub issues.

Nog iets belangrijks: mogen we schrijfrechten krijgen voor INBO gerelateerde projecten? Dit zou handig zijn in het geval van het ontdekken van kleine fouten/aanpassingen in de mapping.

**Comment by damianooldoni** [comment]
Lisenka's answer:

> Dag Damiano,
Het is mogelijk om deze datum vast te zetten. De beheerder van de site moet hiervoor wel een aantal dingen vast voorbereiden, waarvoor hij nog wat informatie nodig heeft:
>1. Om welke soorten gaat het precies.
>2. Welke verschillende kleuren zijn er voor de ringen gebruikt.
> 3. Zijn er bepaalde kenmerken in de inscriptie. Bijvoorbeeld altijd een punt of altijd beginnend met een bepaalde letter of cijfer etc.
> 
> Het is uiteraard mogelijk om schrijfrechten te krijgen voor de INBO gerelateerde projecten.

**Comment by damianooldoni** [comment]
> 1. Om welke soorten gaat het precies.  

Overview `bird_euring` and how many birds for each value:

bird-euring | n_birds
--- | ---
00720 | 170
04560 | 80
05910 | 5327
05920 | 4001
05922 | 39
05926 | 10
not defined | 43

These values could slightly change as the INBO experts could ring new birds in the meanwhile.

> Welke verschillende kleuren zijn er voor de ringen gebruikt.  

Here below the color we have. Only colors of last rings are available: changed rings will appear in spreadsheet without color information.

RingKleurCode | InscriptieKleurCode | n_birds
--- | --- | ---
B | W | 9332
G | W | 212
W | Z | 161
Y | Z | 2
Z | Y | 1
not available | not available | 50

> Zijn er bepaalde kenmerken in de inscriptie. Bijvoorbeeld altijd een punt of altijd beginnend met een bepaalde letter of cijfer etc.

You can check and download the most updated version of `crbirding_birds` here:
https://raw.githubusercontent.com/inbo/sovon/master/data/processed/crbirding_birds.tsv
This file is in this folder within this repository: [./data/processed/](https://github.com/inbo/sovon/tree/master/data/processed).

The point you see sometimes in `bird_shorthand` is **always**  for improving readability.
Very important: we have the version without point if you think it will ease the data transfer! Just let me know which version you prefer.

**Comment by damianooldoni** [comment]
Lisenka wrote:
>  Is de kleur van de ring afhankelijk van de vogelsoort of worden alle kleuren bij alle soorten gebruikt?

**Comment by damianooldoni** [comment]
I don't think so. See here below the situation we have in our database:

crbirding color | bird_euring values
--- | ---
B | 05910,05920,05922,05926
G | 00720           
N | 05910
W | 04560
Y | 05910,05920
.  | 05910,05920,05922

@EricStienen : I think you can confirm it, right?

**Comment by damianooldoni** [comment]
Lisenka:
> Welke kleuren worden er gebruikt voor de Aalscholvers en de Kluten (00720 en 04560)?

**Comment by damianooldoni** [comment]
Sorry, Lisenka. Indeed, the table above was not complete. 
I updated it.

00720 gets G and 04560 gets W.

**Comment by EricStienen** [comment]
confirmed

**Comment by damianooldoni** [comment]
Question for Lisenka: 
our users will have to make an account on https://submit.cr-birding.org/ to add new observations. It would be nice to couple the new user accounts with the old ones. 
Very likely we are not the first ones with such question: how did you solve it? Should we ask them to send an e-mail to you (and us) in order to complete the coupling? Any other idea? Thanks.

**Comment by damianooldoni** [comment]
Lisenka is informed:
> Ik zal ook informeren over het koppelen van de accounts van de oude waarnemingen en de waarnemingen.

Stay tuned...

**Comment by damianooldoni** [comment]
New data dump sent to Lisenka just now based on mapping at this stage of repo:
c126ee300987a58c6f7e4db43d28257fae60e775

Double e-mail (#88) still present and removed manually from user and observation data.

**Comment by damianooldoni** [comment]
Lisenka steps to go forward with import:

Ik heb net doorgekregen dat de users al in submit.crbirding.org zitten. De ringgegevens en waarnemingen worden waarschijnlijk vandaag of morgen toegevoegd. Zodra ze zijn toegevoegd zal ik het doorgeven.

Er waren nog een aantal kleine dingetjes. We hebben ze voor nu prima zelf op kunnen lossen, maar in de toekomst is het de bedoeling dat projectcoördinatoren zelf de gegevens kunnen uploaden, dus het is wel handig als jullie hiervan op de hoogte zijn.

## crbirding_users

1. email moet uniek zijn, in enkele gevallen was dat niet het geval en heb ik de user met de meeste waarnemingen toegewezen aan de waarneming.

2. country `UK` moet worden `GB` (we gebruiken de officiële ISO landencodes)

## crbirding_birds

1. In veel gevallen ontbraken de ringcentrales. Deze hebben we met grote waarschijnlijkheid wel in kunnen vullen.
2. Twee onvolledige ringnummers (alleen de beginletter bekend) zijn vervallen.
3. Voor HJ...907738 kunnen we geen centrale vinden. Zou dit H...907738 kunnen zijn? Hij is op dezelfde datum geringd als H...907737 en H...907739.

**Deze dingen hoeven dus niet in het huidige bestand aangepast te worden.**

## Projecten

Voor de projecten moeten we weten wie de coördinator wordt. (één per project, aanvullende coördinatoren kunnen op de achtergrond)

Verder zijn er voor de projecten nog extra dingen die toegevoegd kunnen worden, mocht dat wenselijk zijn:

1. er kan voor de projecten een omschrijving worden toegevoegd over waarom er wordt geringd. Een klein stukje achtergrond. De tekst moet dan in ieder geval in het Engels en het liefst ook Nederlands worden aangeleverd. Mocht de tekst ook in andere talen beschikbaar zijn (zoals Frans) dan kan deze ook worden toegevoegd.
2. zijn er websites waar de waarnemers meer kunnen lezen over het project of de soort die jullie willen toevoegen?
3. welke ringlocaties moeten er worden aangegeven? (volstaat Belgium, of moet er meer detail worden gegeven).
4. Indien gewenst kan het email adres van de coördinator anders zijn dan die van zijn/haar account. (bijvoorbeeld privé email adres voor het account en werkmail voor coördinator).
5. Eventueel kunnen social media account worden opgenomen.

**Comment by EricStienen** [comment]
HJ...907738 is inderdaad H...907738!

ik zal een stukje tekst schrijven voor de grote meeuwen. Heb het momenteel erg druk met het broedseizoen. Kan dat ook nog wachten? Belangrijkste is dat de invoersite zo snel mogelijk in de lucht gaat. Onze invoer ligt momenteel stil en hoe langer we wachten, hoe meer bulkwerk er op ons zal wachten.

 Ik weet niet waarvoor je de ringlocatie wil gebruiken, maar de exacte locatie staat telkens bij elke vogel (Damiano? samenvoeging van "plaats gemeente en plaats toponiem" bij actie aanbrengen klerurring.

**Comment by damianooldoni** [comment]
> HJ...907738 is inderdaad H...907738!

Great.

> ik zal een stukje tekst schrijven voor de grote meeuwen. Heb het momenteel erg druk met het broedseizoen. Kan dat ook nog wachten? Belangrijkste is dat de invoersite zo snel mogelijk in de lucht gaat. Onze invoer ligt momenteel stil en hoe langer we wachten, hoe meer bulkwerk er op ons zal wachten.

I think so. I will ask to Lisenka. But I am quite sure it is not urgent.
 
> Ik weet niet waarvoor je de ringlocatie wil gebruiken, maar de exacte locatie staat telkens bij elke vogel (Damiano? samenvoeging van "plaats gemeente en plaats toponiem" bij actie aanbrengen klerurring.

Indeed. We have a place for each observation (field or ringing), e.g. `"Zeebrugge, Voorhaven: Kleine Vlakte"`. I think Lisenka means something else, probably at project level? I will ask her immediately. @EricStienen : I will let you know asap.

**Comment by damianooldoni** [comment]
Lisenka's answer:
> Ik bedoelde met ringlocatie inderdaad project level. Worden ze (per soort) allemaal binnen een bepaald gebied in België geringd?

 @EricStienen ? what could you say about it? At least for gulls...

> Wat ik nog wel echt moet weten is welke mensen er als projectleider bij de verschillende soorten moeten worden aangegeven. Het gaat dan om de verschillende meeuwen, de aalscholvers en de kluut.

@EricStienen: I am contacting Filiep en Geert

**Comment by EricStienen** [comment]
ringlocatie in geval van meeuwen = Vlaanderen

Kunnen er meerdere projectleiders zijn? In het geval van de meeuwendatabase wordt de invoer,  de controle en de validatie van de gegevens gedaan door 2 mensen! Marc Van de walle EN Eric Stienen. Of staat dat los van de bevoegheden van projectleider? ALs het slechts een informele titel is dan best mijn naam (Eric Stienen) als projectleider bij de grote meeuwen opnemen.

**Comment by damianooldoni** [comment]
Lisenka:
> Er is per project één projectleider, maar er kunnen op de achtergrond meerdere coördinatoren zijn. Dus ik zal @EricStienen als projectleider doorgeven en Marc van de Walle als extra coördinator.

**Comment by damianooldoni** [comment]
Data transfer is too complex to be further discussed in this issue. I close this one to open new, smaller ones.
