### ISSUE TITLE
Final check sovon field MRI

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#69]
@EricStienen : Could you please double check this table according to the meaning that SOVON gives to this field (see below, from https://github.com/inbo/cr-birding/issues/47#issue-416696738)? It should be ok now, but I would like to ping you for final check. As discussed, not all combinations will be mapped, and, as already said, it is not necessary.

> Eigenlijk is de metal ring information (MRI) alleen gemaakt voor metalen ringen, maar omdat er bij Euring vergelijkbare code is voor vogels waarbij alleen kleurringen zijn gebruikt, gebruiken we in dit geval MRI ook maar voor de kleurringen.

1. `rngkl`: MRI = 2 
2. `rngme` only: MRI = 1
3. `veld` (only or with any other present action): MRI = 4 
4. `me` (only or with any other present action): MRI = 4 
5. `br` only: MRI = 4
6. `dood` only: MRI = 4
7. `br` and `dood`: MRI = 4
8. `meweg` only: MRI = 4
9. `vang`: MRI = 4 or 5
10. `vangl`: MRI = 4 or 5

rngkl | rngme | klgev | br | vang | dood | klweg | veld | meweg | me | vangl | ziek | sovon_MRI
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
 |  |  |  |  | vang |  |  |  |  |  |  |  | 5
 |  |  |  |  |  |  |  | veld |  |  |  |  | 4
rngkl | rngme |  |  |  |  |  |  |  |  |  |  | 2
 |  |  |  | br |  |  |  |  |  |  |  |  | 4
 |  |  |  | br |  |  | klweg |  |  |  |  |  | 
 |  |  |  |  |  |  |  |  |  | me |  |  | 4
 |  |  |  |  |  | dood |  |  |  |  |  |  | 4
 |  |  |  |  |  |  | klweg |  |  | me |  |  | 4
rngkl |  |  |  |  |  |  |  |  |  |  |  | 2
 |  | rngme |  |  |  |  |  |  |  |  |  |  | 1
 |  |  | klgev |  |  |  |  |  |  |  |  |  | 
 |  |  |  |  |  |  |  | veld | meweg |  |  |  | 4
 |  |  |  |  | vang |  |  |  |  |  |  |  | 4
 |  |  |  |  |  |  |  |  | meweg |  |  |  | 4
 |  |  |  |  |  |  |  |  |  |  | vangl |  | 4
 |  |  |  |  | vang |  |  |  | meweg |  |  |  | 5
 |  |  |  |  | vang |  | klweg |  |  |  |  |  | 5
 |  |  |  |  |  |  |  |  |  |  |  | ziek | 
 |  | rngme |  |  | vang |  |  |  |  |  |  |  | 1
 |  |  |  | br |  |  |  |  | meweg |  |  |  | 
 |  |  |  |  |  | dood |  |  | meweg |  |  |  | 
 |  |  |  |  |  | dood | klweg |  |  |  |  |  | 
 |  |  |  | br |  | dood |  |  |  |  |  |  | 4
 |  |  |  |  |  |  | klweg |  |  |  |  |  | 
 |  |  |  | br |  |  |  | veld |  |  |  |  | 4
 |  |  |  |  |  |  | klweg | veld |  |  |  |  | 4
rngkl | rngme |  |  |  |  |  |  |  |  |  | ziek | 2
 |  |  |  |  | vang |  | klweg |  |  |  |  |  | 4
 |  |  |  |  |  |  |  |  |  |  | vangl | ziek | 5

Up to now: 
number of observations without MRI : 144 or 0.1% of all observations.

**Comment by EricStienen** [comment]
NOTE: I read MRI as CRI (Colour Ring Information)


rngme only: MRI = 1 ---> since we use MRI for colour rings here (=CRI), MRI should be "NA" for rngme.
"me" only or "**me and any other combination**": MRI = 4 ---> MRI = 0 
rngme and ringkl ---> MRI =2
klweg only --> MRI =0
br only **or any combination with br**: MRI = 4

**Comment by damianooldoni** [comment]
Ah, I interpreted MRI as a combination of the two. I asked Lisenka to have a phone call. I hope to have a final decision about it very soon. Their original idea was the following: https://github.com/inbo/cr-birding/issues/47#issuecomment-469256635. I found it overkilling the problem and also not ideal as we don't have the full chronology of metal rings. I find your idea simple and effective. It seems however, that SOVON never use code MRI = 0 and they are not keen to use it. A phone call will surely solve this issue.

**Comment by damianooldoni** [comment]
Lisenka's answer via e-mail confirms my interpretation and the fact that MRI = 0 is never used by them, as it would mean that the bird has no rings at all. See answer below:

> Voor de site interpreteren wij inderdaad metal ring informatie als een combinatie van metaal en kleur informatie, dit omdat Euring geen goed veld heeft om kleurring informatie aan te geven. Het is verre van ideaal, maar omdat de meeste vogels met kleurringen ook een metalen ring hebben werkt het over het algemeen wel.
> Als ik het goed begrijp is het probleem dat mijn uitleg in de comment in issue #47 niet al jullie observaties dekt? Deze kunnen we waarschijnlijk wel onder andere categorieën indelen.

 

> Uit de tabel in issue https://github.com/inbo/cr-birding/issues/69#issue-424254576 maak ik op dat er voor klweg (kleurring weg?) nog geen MRI code wordt toegewezen. Ik denk dat we dit het beste als herringing kunnen zien. Dus dan zou de MRI code als 5 worden gezien en bird_rings_changed wordt dan 1. In plaats van dat de nieuwe kleurringcode dan bij de vangst wordt ingevuld, wordt deze leeg gelaten.

> Daarnaast zie ik dat meweg (metalen ring weg?) ook geen MRI code oplevert. Hier heeft Euring gelukkig wel een code voor, namelijk MRI code 6. Als de vogel dood is wordt hier gewoon MRI 4 gebruikt.

> Ik kan er niet helemaal uitkomen wat `br` betekent en wat dit voor invloed kan hebben op de MRI.

> Ik snap dat deze manier van invullen een beetje overdreven lijkt, maar op deze manier kunnen we alle informatie goed invullen. Over het algemeen hebben we ook alleen maar ringvangsten van vogels met zowel een metalen ring als een kleurring en de bijbehorende observaties, dus dan is het een stuk makkelijker om in te vullen.

@EricStienen : nice to know that all `br` have MRI 4. I added it to table. 
I also updated it based on #66: all observations with any combinations of `meweg` have MRI = 4 as color ring is present. `vang`+ `meweg` got 5 just because during the catching the color ring has been changed, so it has nothing to do with `meweg` but with the mapping of `vang` action, which can be 4 or 5 depending on date of applying color rings as defined in `crbirding_birds`.

See updated table here below:

rngkl | rngme | klgev | br | vang | dood | klweg | veld | meweg | me | vangl | ziek | sovon_MRI
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
 |  |  |  |  | vang |  |  |  |  |  |  |  | 5
 |  |  |  |  |  |  |  | veld |  |  |  |  | 4
rngkl | rngme |  |  |  |  |  |  |  |  |  |  | 2
 |  |  |  | br |  |  |  |  |  |  |  |  | 4
 |  |  |  | br |  |  | klweg |  |  |  |  |  | 4
 |  |  |  |  |  |  |  |  |  | me |  |  | 4
 |  |  |  |  |  | dood |  |  |  |  |  |  | 4
 |  |  |  |  |  |  | klweg |  |  | me |  |  | 4
rngkl |  |  |  |  |  |  |  |  |  |  |  | 2
 |  | rngme |  |  |  |  |  |  |  |  |  |  | 1
 |  |  | klgev |  |  |  |  |  |  |  |  |  | 
 |  |  |  |  |  |  |  | veld | meweg |  |  |  | 4
 |  |  |  |  | vang |  |  |  |  |  |  |  | 4
 |  |  |  |  |  |  |  |  | meweg |  |  |  | 4
 |  |  |  |  |  |  |  |  |  |  | vangl |  | 4
 |  |  |  |  | vang |  |  |  | meweg |  |  |  | 5
 |  |  |  |  | vang |  | klweg |  |  |  |  |  | 5
 |  |  |  |  |  |  |  |  |  |  |  | ziek | 
 |  | rngme |  |  | vang |  |  |  |  |  |  |  | 1
 |  |  |  | br |  |  |  |  | meweg |  |  |  | 4
 |  |  |  |  |  | dood |  |  | meweg |  |  |  | 4
 |  |  |  |  |  | dood | klweg |  |  |  |  |  | 
 |  |  |  | br |  | dood |  |  |  |  |  |  | 4
 |  |  |  |  |  |  | klweg |  |  |  |  |  | 
 |  |  |  | br |  |  |  | veld |  |  |  |  | 4
 |  |  |  |  |  |  | klweg | veld |  |  |  |  | 4
rngkl | rngme |  |  |  |  |  |  |  |  |  | ziek | 2
 |  |  |  |  | vang |  | klweg |  |  |  |  |  | 4
 |  |  |  |  |  |  |  |  |  |  | vangl | ziek | 5

@EricStienen : it seems also clear that SOVON would like to have a MRI code for all observations. This is maybe possible if we check the notes of observations linked to unmapped actions. They are linked to very few observations so it will not take so much time for deciding the MRI code. I will discuss them via separate issues and I will update the MRI mapping table based on the decisions taken. I will ping you very soon.

**Comment by EricStienen** [comment]
ok

**Comment by damianooldoni** [comment]
New table:

rngkl | rngme | klgev | br | vang | dood | klweg | veld | meweg | me | vangl | ziek | sovon_MRI
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
 |  |  |  |  | vang |  |  |  |  |  |  |  | 5
 |  |  |  |  |  |  |  | veld |  |  |  |  | 4
rngkl | rngme |  |  |  |  |  |  |  |  |  |  | 2
 |  |  |  | br |  |  |  |  |  |  |  |  | 4
 |  |  |  | br |  |  | klweg |  |  |  |  |  | 4
 |  |  |  |  |  |  |  |  |  | me |  |  | 4
 |  |  |  |  |  | dood |  |  |  |  |  |  | 4
 |  |  |  |  |  |  | klweg |  |  | me |  |  | 4
rngkl |  |  |  |  |  |  |  |  |  |  |  | 2
 |  | rngme |  |  |  |  |  |  |  |  |  |  | 1
 |  |  | klgev |  |  |  |  |  |  |  |  |  | 4
 |  |  |  |  |  |  |  | veld | meweg |  |  |  | 4
 |  |  |  |  | vang |  |  |  |  |  |  |  | 4
 |  |  |  |  |  |  |  |  | meweg |  |  |  | 4
 |  |  |  |  |  |  |  |  |  |  | vangl |  | 4
 |  |  |  |  | vang |  |  |  | meweg |  |  |  | 5
 |  |  |  |  | vang |  | klweg |  |  |  |  |  | 5
 |  |  |  |  | vang |  | klweg |  |  |  |  |  | 2
 |  |  |  |  |  |  |  |  |  |  |  | ziek | 4
 |  | rngme |  |  | vang |  |  |  |  |  |  |  | 1
 |  |  |  | br |  |  |  |  | meweg |  |  |  | 4
 |  |  |  |  |  | dood |  |  | meweg |  |  |  | 4
 |  |  |  |  |  | dood | klweg |  |  |  |  |  | 4
 |  |  |  | br |  | dood |  |  |  |  |  |  | 4
 |  |  |  |  |  |  | klweg |  |  |  |  |  | 4
 |  |  |  | br |  |  |  | veld |  |  |  |  | 4
 |  |  |  |  |  |  | klweg | veld |  |  |  |  | 4
rngkl | rngme |  |  |  |  |  |  |  |  |  | ziek | 2
 |  |  |  |  | vang |  | klweg |  |  |  |  |  | 4
 |  |  |  |  |  |  |  |  |  |  | vangl | ziek | 5

**Comment by damianooldoni** [comment]
Lisenka added this, based on what she also wrote in https://github.com/inbo/cr-birding/issues/47#issuecomment-469256635:
> Uit de tabel in issue #69 maak ik op dat er voor klweg (kleurring weg?) nog geen MRI code wordt toegewezen. Ik denk dat we dit het beste als herringing kunnen zien. Dus dan zou de MRI code als 4 worden gezien en `bird_rings_changed` wordt dan 1. In plaats van dat de nieuwe kleurringcode dan bij de vangst wordt ingevuld, wordt deze leeg gelaten.

> Daarnaast zie ik dat meweg (metalen ring weg?) ook geen MRI code oplevert. Hier heeft Euring gelukkig wel een code voor, namelijk MRI code 6. Als de vogel dood is wordt hier gewoon MRI 4 gebruikt.
