### ISSUE TITLE
Assign MRI code: action klweg only

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#70]
There are just 7observations coupled to action `klweg` only. Here below some details:

Opmerking | KleurringNummer | Datum
--- | --- | ---
omgeringd met NL kleurring G//T | DUAK | 2016-05-18       
F.CAV | FCAV | 2009-10-06
blauw 83 | GGAS | 2018-04-28       
wordt Nederlands HG, metaal is gebleven | HDAC | 2017-05-17           
omgeringd met NL kleurring | LZAZ | 2016-05-20   
wordt gevangen en NPAF wordt 8X | NPAF | 2015-05-30
wordt Nederlands H5, metaal is gebleven | NRAZ | 2017-05-23

It seems to me they just got a Dutch or Belgian new **color** ring.
We can map it to MRI = 2: "ring added (where no ring was present), definitely on tarsus."
I deliberately omitted the word _metal_ in description of MRI value to avoid misunderstandings.

For the not Dutch rings (2nd, 3rd and 6th) should they get action `vang` as they got a new ring? As far as I know, changing color ring or applying a new one (but not the very first one!) is linked to action `vang` (or `vangl`).

@EricStienen : what do you think?

**Comment by EricStienen** [comment]
right! FCAV lost its complete leg where the colour was attached.

**Comment by EricStienen** [comment]
?

**Comment by damianooldoni** [comment]
Temporarily mapped as MRI = 4, waiting for a short meeting with @EricStienen about. It is still a small problem as it is just 7 observations. 4 out of 7 are emigrants, as explained in this issue: https://github.com/inbo/cr-birding/issues/53. For these observations we gave MRI = 4, as they were related to action `br`.

**Comment by EricStienen** [comment]
problem of FCAV solved at DB- level!

**Comment by damianooldoni** [comment]
They are all emigrants except for FCAV. MRI = 4
