### ISSUE TITLE
Assign MRI code: action klweg and dood

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#71]
Opmerking | KleurringNummer | Datum
--- | --- | ---
Gedood door windturbine, kleurring was NIET meer aanwezig! | BVAF | 2001-02-05
NA | DCAZ | 2017-05-24

If metal ring still present (as I assume) then it is still MRI = 4.
About DCAZ, no idea.

@EricStienen : what do you think?

**Comment by EricStienen** [comment]
the same for DCAZ, the metal ring was found on a dead bird, but colour ring was no longer present.

**Comment by damianooldoni** [comment]
Thanks @EricStienen !
So, based on mixed interpretation of SOVON, we can assume MRI = 4. The field `condition` will identify them as dead.

**Comment by EricStienen** [comment]
indeed MRI=4 and condition=dead
