### ISSUE TITLE
Assign MRI code: action klgev

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#72]
Opmerking | KleurringNummer | Datum
--- | --- | ---
datum fictief | AABC | 2014-09-01
geantidateerd, vondst was op 17/05/17 | ABBD | 2016-09-01
geantidateerd: kleurring gevonden op 06/06/17 | ANOZ | 2016-09-01
geantidateerd | AROU | 2016-09-01
NA | ASAA | 2000-07-16
NA | ASAF | 2004-05-28
geantidateerd (vondst was op 17/09/17) | ASOL | 2016-09-01
zonder enige resten vogel | AVOC | 2016-10-16
NA | AXAD | 2010-03-17
datum fictief | BABC | 2012-09-01
geantidateerd, vondst was in 2013 | BABG | 2011-09-01
geantidateerd, vondst was op 27/02/18 | BCOM | 2017-09-01
NA | BDAZ | 2002-06-12
geantidateerd (vondst was op 12/01/18) | BHOB | 2017-09-01
geantidatteerd, vondst was in 2018 | BSOU | 2017-09-01
geantidateerd (vondst was op 17/09/17) | BUOJ | 2017-09-01
CV.AL | CVAL | 2016-05-12
Kleurring quasi onbeschadigd, dus lijkt waarschijnlijk dat die al vanaf 2006 in het veld lag | DRAN | 2008-05-12
ring teruggevonden in opvanggebied (groot vak) | GDAY | 2010-10-03
G.KAF niet uitgevlogen in 2007 | GKAF | 2008-06-22
NA | GPS04 | 2018-05-18
geantidateerd, enkel kleurring gevonden op 10/05/13 | HNAL | 2008-09-01
NA | HRAD | 2010-04-16
geantidateerd, ring gevonden op 23 okt 2012 | NCAV | 2010-09-01
R.FAT | RFAT | 2017-11-04
geantidateerd, vondst was in 2016 | RGAL | 2014-09-01
geantidateerd (20/04/17) | RHAB | 2014-09-01
NA | SAAX | 2013-08-25
wsl pullus van vorig jaar | TMAZ | 2012-05-22
NA | TSAT | 2011-09-01
ring gevonden in 2013 > geantidateerd | TVAV | 2011-09-01
NA | UGAD | 2013-06-05
ring gevonden in 2013 > geantidateerd | UNAG | 2012-09-01
NA | ZBAT | 2016-05-03
zonder enige resten vogel | ZLAH | 2016-10-16
gemeld op 24 sep | ZVAZ | 2015-09-01

So, they are dead birds with a fictieve death date, right?
I would map them as:
MRI = 4 (ring already present)

I am also wondering about the field condition: these birds are dead, so they should get condition = 1?

The mapping of condition up to now is the following:
1. `dood`: condition = 1
2. `ziek`: condition = 4
3. `rngkl`, `rngme`, `vang`, `vangl`: condition = 8
4. `veld`, `me`, `meweg`, `br`: condition = 7

@EricStienen : does my reasononing make sense?

**Comment by EricStienen** [comment]
yes you are completely right. All the listed birds should have MRI=4 and condition = 1.
