### ISSUE TITLE
Assign MRI code: action ziek only

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#73]
There are 80 observations related to action `ziek`: based on SOVON's mixed interpretation of MRI (MRI = metal/color ring information, see https://github.com/inbo/cr-birding/issues/69#issuecomment-476554937) I would assign them MRI value 4 as color and/or were still present.
The field `condition` would take care of uniquely identify this observations (we mapped them as condition 4)
For an overview of the observations we speak about, see file in attachment: [obs_ziek_only.txt](https://github.com/inbo/cr-birding/files/3008296/obs_ziek_only.txt)

@EricStienen : what do you think?

**Comment by EricStienen** [comment]
yes all of them should be MRI=4
