### ISSUE TITLE
assign MRI action vang + klweg

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#74]
vang + klweg -> MRI : 2

**Comment by damianooldoni** [comment]
A little note to add:

`vang` + `klweg` appears 6 times in observation table. This combination of actions is not enough to assign 2. It should also be coupled to a "real ringing" in ring table. 

This holds true for 4 out of 6 cases. For the other two, the ringer seems to not have added any new color ring. I speak about birds with `Nummer` = `LFAV` and `GVAX` in `tblKleurring`.

Nummer | NummerNieuw | NummerDesc
--- | --- | ---
LFAV | LFAV | LFA.V
GVAX | GVAX | GVA.X

In case of observation of `GVAX` there is a note: `omgekat naar W-5|4`.

@EricStienen : could you please check these two birds? If new color ring not added, then MRI -> 4 as metal ring is still present.

**Comment by EricStienen** [comment]
GVAX got a new Dutch colour ring (W: 5|4). I can not find any details for LFAV  (only that the bird was caught on the nest and only had a metal ring, so it lost its colour ring), but Roland-Jan who caught the bird in Holland normally gives each bird that he got in his hands a new Dutch colour ring. I did send him a mail, but for now I think we can safely assume that it got a new Dutch colour ring.

**Comment by damianooldoni** [comment]
Thanks @EricStienen : both "emigrants" (at least GVAX), so no need to add extra row in `cr-birding_birds` and by consequence MRI = 4 instead of 2. Still nice to hear more for being sure about.
