### ISSUE TITLE
Meaning of bird_sex in obs table

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#75]
Based on https://github.com/inbo/cr-birding/issues/40#issuecomment-476673798, I was thinking about the meaning of `bird_sex` in `cr-birding_observations`. Has the interpretation of this field changed as well?
Up to now it is the same as in `cr-birding_birds`:
> •	Bird_sex: in deze kolom wordt het geslacht van de geringde vogel ingevuld. Deze is gelijk aan de kolom bird_sex op het tabblad crbirding_birds

At INBO we think it would be more meaningful to have the sex as recorded by the observer.

**Comment by damianooldoni** [comment]
Lisenka's answer:

> Daar kun je inderdaad sex as recorded by the observer invullen. Ik ga gelijk de regel in het uitleg bestand aanpassen…

**Comment by damianooldoni** [comment]
@EricStienen : trying to find sex column in `tblWaarneming` but I don't find it. 

Asked to Lisenka what to do with it: I think we should leave it empty.

**Comment by damianooldoni** [comment]
Lisenka:
> Je kunt de kolom prima leeglaten. Een andere optie is om er een U (unknown) in te vullen.

**Comment by damianooldoni** [comment]
I agree with Lisenka: it should be `U` unless @EricStienen , you can find the mysterious column :smile: 
I was quite sure there was such column but I am wrong, it seems. Nevermind...

**Comment by EricStienen** [comment]
In our INBO-database we did not fill in the sex as reported by the observer (but note that sex is used in the bird-table). So indeed you can add a "u" in all cases, but leave the option open for future observations.

**Comment by damianooldoni** [comment]
@EricStienen : thanks. Indeed, the field exists both in template and in final file as well.
