### ISSUE TITLE
assign MRI action vang + meweg

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#76]
Similar to #74 , we have combination of actsion `vang` + `meweg`.
This happens just one time. Checking the notes, we can see that a new metal ring has been applied, so it should be MRI = 1, same value we assigned for observations with action `rngme`.

Here below details from `tblWaarneming` table:

Datum |KleurringNummer | Opmerking
--- | --- | ---
2011-05-24 | AKAU | oud metaal L89066 was niet aanwezig, L913152 aangebracht

However, I see also that the color ring has also been changed at the same time (AKAU -> NGA.B). As we are color oriented, I would leave the actual value: MRI = 5.

@EricStienen : can you confirm it?

**Comment by EricStienen** [comment]
confirmed
