### ISSUE TITLE
How action combinations collapse into fields MRI, condition and status

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#77]
This table is based on the action mapping in https://github.com/inbo/cr-birding/issues/69#issuecomment-477518920.

sovon_status | sovon_condition | sovon_MRI | action_combinations
--- | --- | --- | ---
`-` | 1 | 4 | `dood`
`-` | 7 | 4 | `klweg`+`me`, `veld`
`-` | 8 | 1 | `rngme`
`-` | 8 | 2 | `rngkl`+`rngme`, `rngkl`
N | 1 | 4 | `br`+`dood`,
N | 7 | 4 | `br`, `br`+`klweg`, `br`+`meweg`, `br`+`veld`
N | 8 | 1 | `rngme`+`vang`
N | 8 | 2 | `vang`+`klweg`
N | 8 | 4 | `vang`, `vang`+`klweg`
N | 8 | 5 | `vang`, `vang`+`meweg`
U | 1 | 4 | `dood`, `klgev`, `dood`+`meweg`, `dood`+`klweg`
U | 4 | 2 | `rngkl`+`rngme`+`ziek`
U | 4 | 4 | `ziek`
U | 4 | 5 | `vangl`+`ziek`
U | 7 | 4 | `veld`, `me`, `klweg`+`me`, `veld`+`meweg`, `meweg`, `klweg`+`veld`
U | 8 | 1 | `rngme`
U | 8 | 2 | `rngkl`+`rngme`, `rngkl`
U | 8 | 4 | `vangl`, `klweg`

##Summary

### Status: 
> All full-grown birds must have a Status code, even if it is the unknown/not recorded code, U.
> Birds ringed as pulli must be coded with a hyphen. 
We decided to use the following values:
- a pullus (`-`), 
- nesting (`N`)
- Unknown (`U`).

### Condition 

> This field codes condition of the bird when found. 

We decided to use the following values: 
- **1**: _Dead but no information on how recently the bird had died (or been killed)._ 
- **4**: _Found sick, wounded, unhealthy etc. and known to have been released (including ring or other mark identified on a bird in poor condition without the bird having being caught)._ 
- **7**: _Alive and probably healthy and certainly released (including ring or other mark identified on a healthy bird without the bird having being caught)._
- **8**: _Alive and probably healthy and released by a ringer (including ring or other mark identified on the bird by a ringer without the bird having being caught). 'A ringer' means any licensed ringer, not just the ringer who ringed that bird._

### MRI (metal ring information)

This field has to be interpreted in a broader sense, as MRI/CRI. So, I strikethrough the word _ metal_ .
We decided to use the following values:
- **1**: _~Metal~ ring added (where no ~metal~ ring was present), position (on tarsus or above) unknown or unrecorded._ Value use for applying metal rings ONLY.
- **2**: _~Metal~ ring added (where no ~metal~ ring was present), definitely on tarsus._ Value used for applying color rings ONLY or color rings AND metal rings.
- **4**: _~Metal~ ring is already present._ We use this value almost always except when 
- **5**: _~Metal~ ring changed._

Not included here, the field `observation_is_capture` which identifies all observations linked to at least one of these actions: `vang`, `vangl`, `rngkl`, `rngme` (ringvangst en hervangst).

@EricStienen : you have the last word.

**Comment by EricStienen** [comment]
I do not fully understand your last sentence "Not included here, the field observation_is_capture which identifies all observations linked to at least one of these actions: vang, vangl, rngkl, rngme (ringvangst en hervangst)."

**Comment by damianooldoni** [comment]
In addition to status, condition and MRI there is also a field called `observation_is_capture` which I didn't add to the table above. 
From Lisenka's notes:
> •	Observation_is_capture: in deze kolom wordt aangegeven of de waarneming een hervangst betreft of dat de kleuring is afgelezen zonder dat de vogel gevangen is. Wanneer het gaat om een hervangst wordt een 1 ingevuld. Is dit niet het geval wordt er een 0 ingevuld. Als het gaat om de ringvangst wordt hier eveneens een 1 ingevuld. 

Mapping of it is documented here: https://inbo.github.io/cr-birding/4_observations.html#capture

It is just a nice field to easily select all "capture" actions. Just that. No real improvement on distinguishing actions in future table.

**Comment by damianooldoni** [comment]
This table has no so much sense anymore as `meweg`, `klweg`, `klgev` and `megev` trigger new rows in `crbirding_birds` table.
