### ISSUE TITLE
More info about rings of great cormorant and pied avocet

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#79]
Lisenka asked:

> Voordat het bestand ingeladen worden moeten eerst de soortprojecten op de site en in de BirdRing app gedefinieerd worden. Hiervoor heeft hij nog wat extra informatie nodig.

> - Bij de aalscholver worden groene ringen gebruikt. Volgens http://www.cr-birding.org/nl/node/719 gaat het om ringen met 3 tekens. Voor de BirdRing app moet gedefinieerd worden waaraan de Belgische ringen herkent kunnen worden. Is er iets waaraan gezien kan worden dat het om een Belgische ring gaat en niet een groene ring met 3 tekens die in een van de andere landen wordt gebruikt.

> - Bij de kluut worden witte ringen gebruikt. Volgens http://www.cr-birding.org/node/818  gaat het om ringen met 4 tekens. Ook hier moet voor de app gedefinieerd worden waaraan de ringen herkent kunnen worden. Volgens crbirding.org gaat het om de codes EAAA-CZZZ. Kunnen de ringen dus herkent worden aan het feit dat ze beginnen met een E of een C?

**Comment by damianooldoni** [comment]
### Identify color rings of cormorants (aalscholvers)
The inscription starts with `K` or `B` and no numbers are present, only three letters. 

### Identify color rings of pied avocets (kluten)
The inscription starts with `E` and the inscription does NOT contain any number, only letters.

Are these features sufficient to identify both uniquely?

**Comment by EricStienen** [comment]
yes that would be sufficient!

**Comment by damianooldoni** [comment]
Lisenka confirmed me via phone that the informations above are sufficient and that this issue can be closed.
