### ISSUE TITLE
Bird ringing date: duplicates in applying bird ring for same datum and bird found

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#8]
While mapping bird ringing date, I found some duplicates in `tbl.Waarneming` which, I think, are anomalous. Same color ring number, same datum should result in one row, doesn't? 
The last column, `AktieCode`, comes from `tbl.tblWaarnemingAktie` and it has been used to filter bird color ringing actions (`rngkl`) from all observations.

Nummer | Datum | EuringCode | LeeftijdCode | KleurringNummer | ... | AktieCode
--- | --- | --- | --- | --- | --- | ---
114631 | 2016-07-13 | 5910 | PU | AVOH | | rngkl
114756 | 2016-07-13 | 5910 | PU | AVOH | | rngkl
123429 | 2017-07-28 | 5910 | PU | BROK | | rngkl
123710 | 2017-07-28 | 5910 | PU | BROK | | rngkl
124558 | 2017-07-11 | 5910 | PU | BVOU | | rngkl
126531 | 2017-07-11 | 5910 | PU | BVOU | | rngkl
124130 | 2017-07-06 | 5920 | PU | CBOC | | rngkl
124962 | 2017-07-06 | 5920 | PU | CBOC | | rngkl
123339 | 2017-07-06 | 5920 | PU | CBON | | rngkl
124967 | 2017-07-06 | 5920 | PU | CBON | | rngkl 
126033 | 2017-07-11 | 5920 | PU | CFOZ | | rngkl
126572 | 2017-07-11 | 5920 | PU | CFOZ | | rngkl
**124365** | **2017-07-10** | **5920** | **J1** | **CGOC** | | **rngkl**
**125207** | **2017-07-10** | **5920** | **PU** | **CGOC** | | **rngkl**
123915 | 2017-07-05 | 5920 | PU | CVOH | | rngkl
124668 | 2017-07-05 | 5920 | PU | CVOH | | rngkl
61169 | 2010-04-28 | 00720 | PU | KSW | | rngkl
61168 | 2010-04-28 | 00720 | PU | KSW | | rngkl
108390 | 2015-07-08 | 5910 | PU | RLAU | | rngkl
109056 | 2015-07-08 | 5910 | PU | RLAU | | rngkl

In bold two ringing actions (`Nummer` = 124365 and 125207) to same bird where a discrepancy about `LeeftijdCode` has been detected too. Same datum, same bird = same age, right?
Eric, Marc: your help is needed :rescue_worker_helmet: Thanks in advance.

**Comment by damianooldoni** [comment]
Eric's answer:

> Opgelost!

**Comment by damianooldoni** [comment]
I confirm it: solved by Eric at db level.
I will still run the check in pipeline:
```r
duplicates_ringing <- obs_and_acts %>%
  filter(raw_AktieCode %in% c("rngkl", "rngme")) %>%
  filter(raw_KleurringNummer %in% (
    obs_and_acts %>% 
      filter(raw_AktieCode %in% c("rngkl", "rngme")) %>%
      group_by(raw_KleurringNummer, raw_Datum, raw_AktieCode) %>%
      count() %>%
      filter(n > 1) %>%
      pull(raw_KleurringNummer))) %>%
  arrange(raw_KleurringNummer)
duplicates_ringing
```

**Comment by damianooldoni** [comment]
I found two new duplicates for applying color ring (action `rngkl`) and metal ring (code `rngme`) for two birds: `FKOU` and `FNOS`. Expecting 2 birds x 2 rings = 4 rows, got 8. 
Here below some more details from `tblWaarneming` coupled to action code from `tblWaarnemingAktie` (last column):

Nummer | Datum | EuringCode | LeeftijdCode | KleurringNummer | ... | AktieCode
--- | --- | --- | --- | --- | --- | ---
134484 | 2018-08-01 | 5920 | J1 | FKOU | | rngkl
134484 | 2018-08-01 | 5920 | J1 | FKOU | | rngme
134483 | 2018-08-01 | 5920 | J1 | FKOU | | rngkl
134483 | 2018-08-01 | 5920 | J1 | FKOU | | rngme
134493 | 2018-08-01 | 5920 | J1 | FNOS | | rngkl
134493 | 2018-08-01 | 5920 | J1 | FNOS | | rngme
134492 | 2018-08-01 | 5920 | J1 | FNOS | | rngkl
134492 | 2018-08-01 | 5920 | J1 | FNOS | | rngme

Observations have been added quite recently: `2018-10-16 14:34:00` and `2018-10-16 14:37:00`.
@EricStienen : as they are just duplicates (same age, same location, etc.) I can reduce them easily, but solving the issue at db level is always welcome.

**Comment by EricStienen** [comment]
Solved at db level. Marc was not very well awake I am afraid.

**Comment by damianooldoni** [comment]
Confirmed, great. I reclose the issue.
