### ISSUE TITLE
Presence of yellow Dutch rings in crbirding_birds

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#82]
Lisenka:
> In crbirding_birds staan twee vogels met gele ringen. Het gaat bij beide om Nederlandse vogels die volgens onze database in Nederland door een Nederlandse ringer met kleurringen zijn geringd. Kan dit kloppen?

**Comment by damianooldoni** [comment]
I see two yellow rings with black inscription: `YN(WE)` and `YN(B0)`. 
Lisenka: do you speak about these two, I think. Is it per se a problem to have Dutch rings in our database?

**Comment by damianooldoni** [comment]
Lisenka:
>Als ik het goed zie zijn het vogels die in België met een Nederlandse(?) metalen ring zijn geringd (want ringing scheme `NLA`), vervolgens in België een kleurring hebben gekregen, die vervolgens in Nederland is vervangen door een nieuwe kleurring?

> Het is op zich nu nog geen probleem, omdat degene die de Nederlandse kleurring heeft toegevoegd nog niet is aangesloten bij submit.crbirding.org. Mocht dit in de toekomst gebeuren, dan kan het zijn dat de vogel ook in zijn database zit en dat ze dubbel in submit.crbirding.org terecht komen.

> Voor de duidelijkheid binnen jullie project (vooral voor de waarnemers) is het misschien beter om ze eruit te halen, vooral omdat het er maar twee zijn en ze hele afwijkende ringen hebben van de rest van de vogels.

**Comment by damianooldoni** [comment]
I understand perfectly. I checked in `crbirding_observations`. We have only 13 observations linked to these two rings, five for `YN(B0)` and eight for `YN(WE)`. Both are gulls.

@EricStienen: what do you think if we
1. export the data of these two birds (users + birds + observations)
2. send them to the Dutch ringer and hits/her organization
3. remove them from our export files `crbirding_birds` and `crbirding_observations` (you don't have to remove from db if you don't want, I just remove them while mapping)
Thanks.

**Comment by EricStienen** [comment]
solved at DB-level! Treated as all other birds that received a new Dutch ring.

**Comment by damianooldoni** [comment]
Great @EricStienen. I can confirm it.
