### ISSUE TITLE
Submitting subspecies

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#83]
Lisenka:
> Het doorgeven van ondersoorten is iets wat op dit moment nog niet 100% werkt, hier is de applicatiebeheerder op dit moment nog mee bezig.

**Comment by damianooldoni** [comment]
For INBO color ring data, this means:

euring code | subspecies | number of rings | number of observations
--- | --- | --- | ---
05922 | Larus argentatus heuglini | 42 | 743
05926 | Larus argentatus michahellis | 14 | 149

**Comment by EricStienen** [comment]
these are not subspecies!

Larus michahellis is already recognised as a species for about 10 years. The official Euring Code is 05926 but there it is still treated as a subspecies (Larus argentatus michahellis). It is time to change that given that this species is also breeding and frequently ringed in The Netherlands. 

05922 is actually NOT  Larus argentatus heuglini!!! We use this code for hybrid gulls (can be all kind of hybrids - often not traceble wich wto species). Euring does not have a code for hybrids of large gulls. I think that 06009 Larus sp. would be the most appropriate code for these birds. So I suggest to change 05922 to 06009!

**Comment by damianooldoni** [comment]
Thanks @EricStienen  for clear answer. I ask to Lisenka whether changing 05922 to 06009 could partly solve the problem and speed up the data transfer.

**Comment by damianooldoni** [comment]
Via phone Lisenka answered:
1. changing 05922 to 06009 is ok
2. we will work in order to have 05926 correctly loaded in database
