### ISSUE TITLE
How to manage old rings without color information

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#84]
Lisenka:
> Bij een aantal van de geringe vogels is de kleur van de kleurring niet aangegeven (bijvoorbeeld L...909920 -> BBAT). Is de kleur hier niet van bekend? Ik zie dat het allemaal herringde vogels zijn waarvan de kleurringcode van de tweede vogel wel klopt. Als de kleur inderdaad niet bekend is moeten we even bekijken hoe we deze in gaan voeren.

**Comment by damianooldoni** [comment]
Indeed, the INBO db table for birds is built in a way that **one row** = **one bird**.
This has important consequences about birds ringed more than once. I don't have information about the colors of the ring and of the inscription for older, changed rings.

@EricStienen : can we assume that older rings have same color of newer rings? Following the example of Lisenka: can we assume that `BBAT` is a blue ring with white inscription as the second ring applied to same bird, `BW(GHA.B)` ? Ring color is species-wise, isn't? I see that all gulls have blue rings with white inscription, all pied avocets have white ring with black inscription, all cormorans have green rings with white inscription. I can perfectly understand that assigning a color to old rings would make things way more easy for everybody...

**Comment by EricStienen** [comment]
All rings containing 4 letters of whcih the third letter is an A are blue rings with white inscription! After you made  a script for these changes, could you mkae me a list with the remaining codes without colours (if any)? I will then change these at the DB-level.

**Comment by damianooldoni** [comment]
I answered to @EricStienen in wrong issue: https://github.com/inbo/cr-birding/issues/81#issuecomment-479038807. Sorry.

**Comment by damianooldoni** [comment]
Color rings with only letters and a `B` at third position got colors. See https://github.com/inbo/cr-birding/issues/81#issuecomment-479365880.

**Comment by damianooldoni** [comment]
The color rings in attachment (from https://github.com/inbo/cr-birding/issues/81#issuecomment-479365880) are foreign rings replaced with blue rings with white letter-only inscription and a `A` or a `O` at third position. 
Questions to Lisenka: 
1. Should we assign a color to them as well?
2. If I understand correctly, assigning them to a project is not a problem as they are old replaced rings. Are still uniqueness problems we have to solve?

[rings_color_still_unknown_with_number.txt](https://github.com/inbo/cr-birding/files/3037641/rings_color_still_unknown_with_number.txt)
[rings_color_still_unknown_left.txt](https://github.com/inbo/cr-birding/files/3037643/rings_color_still_unknown_left.txt)

**Comment by damianooldoni** [comment]
Eric suggested in https://github.com/inbo/cr-birding/issues/81#issuecomment-479395455 to not assign any color to the rings of group 3 (see group here https://github.com/inbo/cr-birding/issues/81#issuecomment-479038807).
What about group 1 then (rings from `rings_color_still_unknown_with_number.txt`)?

**Comment by EricStienen** [comment]
idem for group 1

**Comment by damianooldoni** [comment]
Lisenka:
> Bij de overige kleurringen waarvan de kleur niet bekend is gaat het om vogels die inmiddels al herringd zijn. Zoals Eric al opmerkt kunnen deze ringen al niet meer afgelezen worden. Als ze geen kleur krijgen zijn ze op dit moment echter niet echt simpel in te lezen in onze website. Het voorstel is dan ook om de kolom bird_shorthand voor de oude ringen met onbekende kleur leeg te laten. Het ringgegeven en eventuele oude waarnemingen van de oude kleurring zullen gewoon opgenomen worden in de database, alleen is de oude kleurring dan niet bekend.

Lisenka's proposal example using history linked to bird with old ring `TY2`:

bird_reference | bird_shorthand | bird_date_begin | bird_date_end
--- | --- | --- | ---
2049 | | 1997-07-05 | 2007-06-06
2049 | BW(GMAJ) | 2007-06-06 | 2013-06-10
2049 | BW(GMAJ) | 2013-06-10 | 

My idea is slightly different. I find better to assign a fictive color to these rings: same color as the new rings instead of leaving it empty. Using same example as before:

bird_reference | bird_shorthand | bird_date_begin | bird_date_end
--- | --- | --- | ---
2049 | BW(TY2) | 1997-07-05 | 2007-06-06
2049 | BW(GMAJ) | 2007-06-06 | 2013-06-10
2049 | BW(GMAJ) | 2013-06-10 | 

Lisenka, @EricStienen : what do you think?

@EricStienen : which note should I add? Can be `foreign_color_ring` a valid option?

**Comment by damianooldoni** [comment]
Via phone, Lisenka finds my alternative ok. @EricStienen , I assume you don't have anything against it. Let me know, thanks.

**Comment by EricStienen** [comment]
no obejections

**Comment by damianooldoni** [comment]
Thanks @EricStienen , I will map it immediately.
