### ISSUE TITLE
EURING code is mandatory: fill in empty ones

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#89]
Lisenka:
> Bij een aantal ringen staat geen soort. Het gaat om een verplicht veld. Kan als de soort niet bekend is de EURING-code voor “Larus spec.” worden ingevuld?

**Comment by damianooldoni** [comment]
Indeed, there are 46 birds where the crbirding field `euring_code` is left empty.

3 birds in INBO table `tblkleurring` have no value `EuringCode`:

Nummer | NummerNieuw | NummerDesc | EuringCode
--- | --- | --- | ---
BGAH | BGAH | BGAH | 
NGAU | NGAU | NGA.U | 
BRAB | BRAB | BRAB | 

One bird has `EuringCode` value `zz`, which we mapped to NA (empty):

Nummer | NummerNieuw | NummerDesc | EuringCode
--- | --- | --- | ---
EAAX | EAAX | EAAX | zz

42 birds have `EuringCode` value `zzz`, which we mapped to NA (empty):

Nummer | NummerNieuw | NummerDesc | EuringCode
--- | --- | --- | ---
BBH | BBH | BBH | zzz
BBJ | BBJ | BBJ | zzz
BBK | BBK | BBK | zzz
BBL | BBL | BBL | zzz
BBM | BBM | BBM | zzz
BBN | BBN | BBN | zzz
BBP | BBP | BBP | zzz
BBR | BBR | BBR | zzz
BBS | BBS | BBS | zzz
BBU | BBU | BBU | zzz
BBT | BBT | BBT | zzz
BCV | BCV | BCV | zzz
BCW | BCW | BCW | zzz
BCX | BCX | BCX | zzz
BCY | BCY | BCY | zzz
BCZ | BCZ | BCZ | zzz
BCU | BCU | BCU | zzz
BCT | BCT | BCT | zzz
BCS | BCS | BCS | zzz
BCR | BCR | BCR | zzz
BCM | BCM | BCM | zzz
BBW | BBW | BBW | zzz
BBV | BBV | BBV | zzz
BBX | BBX | BBX | zzz
BBY | BBY | BBY | zzz
BCC | BCC | BCC | zzz
BCF | BCF | BCF | zzz
BCE | BCE | BCE | zzz
BBZ | BBZ | BBZ | zzz
BCA | BCA | BCA | zzz
BCB | BCB | BCB | zzz
BCN | BCN | BCN | zzz
BCP | BCP | BCP | zzz
BCL | BCL | BCL | zzz
BCK | BCK | BCK | zzz
BCJ | BCJ | BCJ | zzz
BEE | BEE | BEE | zzz
BEF | BEF | BEF | zzz
BEH | BEH | BEH | zzz
BEA | BEA | BEA | zzz
BEC | BEC | BEC | zzz
BEB | BEB | BEB | zzz


@EricStienen : you don't have to change them at DB level if you can provide me a simple rule to map the EURING code of these birds. Thanks in advance.

**Comment by EricStienen** [comment]
zz = Avocet and zzz = great cormorant

**Comment by damianooldoni** [comment]
Great! Thanks @EricStienen .

**Comment by damianooldoni** [comment]
@EricStienen : there is still the problem of three birds with empty EURING code mentioned at the very beginning of my previous comment: https://github.com/inbo/cr-birding/issues/89#issuecomment-479825392:

Nummer | NummerNieuw | NummerDesc | EuringCode
--- | --- | --- | ---
BGAH | BGAH | BGAH | 
NGAU | NGAU | NGA.U | 
BRAB | BRAB | BRAB | 

Are they gulls, isn't? Which supspecies? or Gull sp.? Thanks.

**Comment by EricStienen** [comment]
NGAU is solved at DB-level. BGAH and BRAB are rings that were applied before I started working at INBO. It is not clear if these rings were used at all. Probably not as suggest by our former volunteer. I suggest that you will delete these two birds from the SOVON-database. I will, however, leave them in the original database with species NA.

**Comment by damianooldoni** [comment]
Thanks you @EricStienen . I will.
