### ISSUE TITLE
ring called FOUT

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#9]
I found a bird in `tblKleurring` with following properties:

Nummer |NummerNieuw | NummerDesc 
--- | --- | ---
FOUT | FOUT | FOUT

All other fields are empty.

Eric, Marc: is there a reason why should it be there? Again, I can filter out easily during the mapping  script if you prefer to leave it in database. Let me know.

**Comment by damianooldoni** [comment]
I see the reason `FOUT` is used: I found 363 observations (rows in table `tblWaarneming`) with `KleurringNummer` equal to `FOUT`. 
Personally I don't see any reason to transport these observations to SOVON. But I understand if you want to maintain it in the INBO database, if you don't want to remove these rows.
So, should I clean it in the preprocessing or do you clean it in the database? Let me know.

**Comment by damianooldoni** [comment]
Eric's answer:

> In principe zou ik die code willen behouden. Als admin zou ik dan een verkeerde aflezing kunnen omzetten naar FOUT. Maar ik denk er nog eens over na.

**Comment by damianooldoni** [comment]
At the moment I remove them, but I added the link to this issue in the pipeline.

**Comment by damianooldoni** [comment]
@EricStienen : as we will get administrator rights on our projects you can always add the right birds and related observations later on directly in cr-birding database. Let me know if this strategy is ok for you. Then I can close this issue.

**Comment by EricStienen** [comment]
OK you can close the issue.
