### ISSUE TITLE
Provide bird_date_end to virtual rings

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#90]
Lisenka:
> Als een ring wordt hergebruikt, geef dan bij de oude vogel behalve een begindatum ook en einddatum op (het gaat om de fictieve ringen)

**Comment by damianooldoni** [comment]
Yes, it makes sense. 

We have for these virtual rings a begin date (SOVON field `bird_date_begin`) but no end date: this means that this virtual ring can still be read, which is not true.

My proposed solution: assign `bird_date_end` = `bird_date_begin`. 

@EricStienen : do you agree?
Lisenka: is it possible or are db constraints for it?

**Comment by damianooldoni** [comment]
Lisenka:
>  Je kunt voor de einddatum van de fictieve ringen voor de zekerheid ook een dag later dan de begindatum kiezen. Dan moet het zeker kunnen.

**Comment by damianooldoni** [comment]
Actually it seems these "virtual rings" are linked to both ringing action (`rngkl`, `rngme`) and `dood` action. So, no need to artificially add a fictive `bird_date_end`. Just use the date linked to observation with action `dood`.  This holds true for 47 out of 50. The remaining 3 rings, `BABG`, `BABC`, `AABC`, are linked to observations with action `klgev`. I don't understand the difference, but I can easily implement it. 

@EricStienen : do you confirm this?

**Comment by damianooldoni** [comment]
There is one (!) virtual ring, `ABBF`, linked only to an observation with action `dood` and no ringing action (`rngkl`, `rngme`). This could be easily solved at DB-level. @EricStienen: could you please do it? Many thanks!

**Comment by EricStienen** [comment]
all solved at DB-level (including ABBF)

**Comment by damianooldoni** [comment]
Many thanks, @EricStienen.

**Comment by damianooldoni** [comment]
Checked: indeed, everything solved at db-level.
