### ISSUE TITLE
Add bird_date_end to dead birds

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#96]
Assign `bird_date_end` to dead birds:
`bird_date_end` = date of observation with action `dood` or `klgev`

**Comment by damianooldoni** [comment]
@EricStienen : I found 7 observations with date after date of death (`dood`). Could you please check them and solve them at db level? Many thanks. This will help by defining a complete and correct sequence of ring begin/end dates in `crbirding_birds`. List here below:

1. Bird with ring `CUOH`: there are two observations with action `dood`: first at 2017-11-02, second 2017-11-07. One of the two should be removed.
2. Bird with ring `DBOM`; `veld` observation at 2018-08-15, while `dood` at 2018-07-29.
3. Bird with ring `DLAW`; `veld` observation at 2013-08-28, while `dood` at 2012-06-01.
4. Bird with ring `FYAP`: `veld` at 2015-10-12, `dood` at 2006-08-15.
5. Bird with ring `LAAD`: `veld` at 2019-02-05, `dood` at 2018-07-17.
6. Bird with ring `SCAV`: `veld` at 2017-05-07, `dood` at 2016-07-17.
7. Bird with ring `YFAW`: `veld` at 2013-08-28, `dood` at 2012-08-22

Meanwhile I perform the check and I remove them from mapping.

**Comment by EricStienen** [comment]
solved ar DB-level

**Comment by damianooldoni** [comment]
@EricStienen : Yes, I confirm that no observations after `dood` are anymore present in DB. 

Observations after `klgev` are possible: I will understand `klgev`  as `klweg`, I will not remove obs occurring after `klweg`.

**Comment by EricStienen** [comment]
Indeed observations are still possible after klweg!

**Comment by damianooldoni** [comment]
Yes, @EricStienen : indeed. Based on "new" mapping, `klgev` or `megev` trigger a new row in SOVON bird table, same as `klweg` or `meweg`, even if not combined with a `vang` action. See https://github.com/inbo/cr-birding/issues/47#issuecomment-480046086
