### ISSUE TITLE
No two klweg allowed without a vang in between

### ISSUE THREAD

**Issue by damianooldoni** [inbo/sovon#98]
The bird `GGAS` is the only one linked to multiple (2) observations with action `klweg` without a `vang` action in between. 

kleurringNummer | Datum | linked actions
--- | --- | ---
GGAS | 2018-04-28 | `klweg` 
GGAS | ... | `veld`
GGAS | ... | `veld`
GGAS | 2018-05-16 | `klweg`, `br`

@EricStienen : Could you please remove action `klweg` from second observation at DB level? It would sensibly ease the mapping of ring sequences. Thanks.

**Comment by EricStienen** [comment]
solved at database level. First klweg was an error and is now removed

**Comment by damianooldoni** [comment]
Thanks. Confirmed. I close the issue.
